package ControlersofBCLC;

import GuiOFBCLC.EnglishBrail;
import GuiOFBCLC.EnglishBrailbySinhala;
import GuiOFBCLC.EnglishBrailbyTamil;
import GuiOFBCLC.SinhalaBrail;
import GuiOFBCLC.SinhalaBrailTBYEnglish;
import GuiOFBCLC.SinhalaBrailTBYTamil;
import GuiOFBCLC.TamilBrail;
import GuiOFBCLC.TamilBrailTranslateBYEnglish;
import GuiOFBCLC.TamilBrailTranslateBYSinhala;

public class ConvertingIntoBraille 
{
    public static void convertSinhlaToBraille(String text,int a) 
    {
        text = text.replace("අ", "⠁");
        text = text.replace("ආ", "⠜");
        text = text.replace("ඇ", "⠷");
        text = text.replace("ඈ", "⠻");
        text = text.replace("ඉ", "⠪");
        text = text.replace("ඊ", "⠔");
        text = text.replace("උ", "⠥");
        text = text.replace("ඌ", "⠳");
        text = text.replace("එ", "⠑");
        text = text.replace("ඒ", "⠢");
        text = text.replace("ඔ", "⠭");

        text = text.replace("ඕ", "⠕⠕");

        text = text.replace("ඓ", "⠈");
        text = text.replace("ඖ", "⠌");

        text = text.replace("ර්", "⠈⠗");
        text = text.replace("රැ", "⠜⠷");
        text = text.replace("රෑ", "⠜⠻");
        text = text.replace("රෟ", "⠗⠳");
        text = text.replace("රූ", "⠗⠳");
        text = text.replace("රා", "⠗⠜");
        text = text.replace("රි", "⠗⠪");
        text = text.replace("රී", "⠗⠔");
        text = text.replace("රෝ", "⠗⠭");
        text = text.replace("රො", "⠗⠕");
        text = text.replace("රෙ", "⠗⠑");
        text = text.replace("රේ", "⠗⠢");
        text = text.replace("රෛ", "⠗⠑⠪");

        text = text.replace("රු", "⠗⠥");//problem
        text = text.replace("ර", "⠗");//problem

        text = text.replace("ං", "⠈⠝");
        //cons
        text = text.replace("න්", "⠈⠝");
        text = text.replace("නා", "⠝⠜");
        text = text.replace("නි", "⠝⠪");
        text = text.replace("නී", "⠝⠔");
        text = text.replace("නෝ", "⠝⠭");
        text = text.replace("නො", "⠝⠕");
        text = text.replace("නෙ", "⠝⠑");
        text = text.replace("නේ", "⠝⠢");
        text = text.replace("නෛ", "⠝⠑⠪");
        text = text.replace("නු", "⠝⠥");
        text = text.replace("නූ", "⠝⠳");
        text = text.replace("නැ", "⠜⠷");
        text = text.replace("නෑ", "⠜⠻");
        text = text.replace("නෟ", "⠝⠳");
        text = text.replace("න", "⠝");

        text = text.replace("හ්", "⠈⠓");
        text = text.replace("හා", "⠓⠜");
        text = text.replace("හි", "⠓⠪");
        text = text.replace("හී", "⠓⠔");
        text = text.replace("හො", "⠓⠭");
        text = text.replace("හෝ", "⠓⠕");
        text = text.replace("හෙ", "⠓⠑");
        text = text.replace("හේ", "⠓⠢");
        text = text.replace("හෛ", "⠓⠑⠪");
        text = text.replace("හු", "⠓⠥");
        text = text.replace("හූ", "⠓⠳");
        text = text.replace("හැ", "⠜⠷");
        text = text.replace("හෑ", "⠜⠻");
        text = text.replace("හෟ", "⠓⠳");
        text = text.replace("හ", "⠓");

        text = text.replace("අන්", "⠄");
        text = text.replace("අහ්", "⠄⠄");/////////--------------------

        text = text.replace("ක්", "⠈⠅");
        text = text.replace("කෑ", "⠜⠻");
        text = text.replace("කා", "⠅⠜");
        text = text.replace("කි", "⠅⠪");
        text = text.replace("කී", "⠅⠔");
        text = text.replace("කො", "⠅⠭");
        text = text.replace("කෝ", "⠅⠕");
        text = text.replace("කෙ", "⠅⠑");
        text = text.replace("කේ", "⠅⠢");
        text = text.replace("කෛ", "⠅⠑⠪");
        text = text.replace("කු", "⠅⠥");
        text = text.replace("කූ", "⠅⠳");
        text = text.replace("කැ", "⠜⠷");
        text = text.replace("කෟ", "⠅⠳");
        text = text.replace("ක්‍ර", "⠈⠅⠗");

        text = text.replace("ක", "⠅");

        text = text.replace("ග්", "⠈⠛");
        text = text.replace("ගා", "⠛⠜");
        text = text.replace("ගි", "⠛⠪");
        text = text.replace("ගී", "⠛⠔");
        text = text.replace("ගො", "⠛⠭");
        text = text.replace("ගෝ", "⠛⠕");
        text = text.replace("ගෙ", "⠛⠑");
        text = text.replace("ගේ", "⠛⠢");
        text = text.replace("ගෛ", "⠛⠑⠪");
        text = text.replace("ගු", "⠛⠥");
        text = text.replace("ගූ", "⠛⠳");
        text = text.replace("ගැ", "⠜⠷");
        text = text.replace("ගෑ", "⠜⠻");
        text = text.replace("ගෟ", "⠛⠳");
        text = text.replace("ග්‍ර", "⠈⠛⠗");
        text = text.replace("ගෞ", "⠛⠑⠥");
        text = text.replace("ග", "⠛");

        text = text.replace("ච්", "⠈⠉");
        text = text.replace("චා", "⠉⠜");
        text = text.replace("චි", "⠉⠪");
        text = text.replace("චී", "⠉⠔");
        text = text.replace("චො", "⠉⠭");
        text = text.replace("චෝ", "⠉⠕");
        text = text.replace("චෙ", "⠉⠑");
        text = text.replace("චේ", "⠉⠢");
        text = text.replace("චෛ", "⠉⠑⠪");
        text = text.replace("චු", "⠉⠥");
        text = text.replace("චූ", "⠉⠳");
        text = text.replace("චැ", "⠜⠷");
        text = text.replace("චෑ", "⠜⠻");
        text = text.replace("චෟ", "⠉⠳");
        text = text.replace("ච්‍ර", "⠈⠉⠗");
        text = text.replace("චෞ", "⠉⠑⠥");
        text = text.replace("ච", "⠉");

        text = text.replace("ජ්", "⠈⠡");
        text = text.replace("ජා", "⠡⠜");
        text = text.replace("ජි", "⠡⠪");
        text = text.replace("ජී", "⠡⠔");
        text = text.replace("ජො", "⠡⠭");
        text = text.replace("ජෝ", "⠡⠕");
        text = text.replace("ජෙ", "⠡⠑");
        text = text.replace("ජේ", "⠡⠢");
        text = text.replace("ජෛ", "⠡⠑⠪");
        text = text.replace("ජු", "⠡⠥");
        text = text.replace("ජූ", "⠡⠳");
        text = text.replace("ජැ", "⠜⠷");
        text = text.replace("ජෑ", "⠜⠻");
        text = text.replace("ජෟ", "⠡⠳");
        text = text.replace("ජ්‍ර", "⠈⠡⠗");
        text = text.replace("ජෞ", "⠡⠑⠥");
        text = text.replace("ජ", "⠡");

        text = text.replace("්‍ය්", "⠈⠽");
        text = text.replace("්‍යා", "⠽⠜");
        // text = text.replace("යි", "⠽⠪");
        //text = text.replace("යී", "⠽⠔");
        text = text.replace("්‍යො", "⠽⠭");
        text = text.replace("්‍යෝ", "⠽⠕");
        text = text.replace("්‍යෙ", "⠽⠑");
        text = text.replace("්‍යේ", "⠽⠢");
        text = text.replace("යෛ", "⠽⠑⠪");
        text = text.replace("්‍යු", "⠽⠥");
        text = text.replace("්‍යූ", "⠽⠳");
        // text = text.replace("යැ", "⠜⠷");
        // text = text.replace("යෑ", "⠜⠻");
        // text = text.replace("යෟ", "⠽⠳");
        text = text.replace("ට්", "⠈⠾");
        text = text.replace("ටා", "⠾⠜");
        text = text.replace("ටි", "⠾⠪");
        text = text.replace("ටී", "⠾⠔");
        text = text.replace("ටො", "⠾⠭");
        text = text.replace("ටෝ", "⠾⠕");
        text = text.replace("ටෙ", "⠾⠑");
        text = text.replace("ටේ", "⠾⠢");
        text = text.replace("ටෛ", "⠾⠑⠪");
        text = text.replace("ටු", "⠾⠥");
        text = text.replace("ටූ", "⠾⠳");
        text = text.replace("ටැ", "⠜⠷");
        text = text.replace("ටෑ", "⠜⠻");
        text = text.replace("ටෟ", "⠾⠳");
        text = text.replace("ට්‍ර", "⠈⠾⠗");
        text = text.replace("ටෞ", "⠾⠑⠥");
        text = text.replace("ට", "⠾");

        text = text.replace("ඩ්", "⠈⠫");
        text = text.replace("ඩා", "⠫⠜");
        text = text.replace("ඩි", "⠫⠪");
        text = text.replace("ඩී", "⠫⠔");
        text = text.replace("ඩො", "⠫⠭");
        text = text.replace("ඩෝ", "⠫⠕");
        text = text.replace("ඩෙ", "⠫⠑");
        text = text.replace("ඩේ", "⠫⠢");
        text = text.replace("ඩෛ", "⠫⠑⠪");
        text = text.replace("ඩු", "⠫⠥");
        text = text.replace("ඩූ", "⠫⠳");
        text = text.replace("ඩැ", "⠜⠷");
        text = text.replace("ඩෑ", "⠜⠻");
        text = text.replace("ඩෟ", "⠫⠳");
        text = text.replace("ඩ්‍ර", "⠈⠫⠗");
        text = text.replace("ඩෞ", "⠫⠑⠥");
        text = text.replace("ඩ", "⠫");

        text = text.replace("ණ්", "⠈⠵");
        text = text.replace("ණා", "⠵⠜");
        text = text.replace("ණි", "⠵⠪");
        text = text.replace("ණී", "⠵⠔");
        text = text.replace("ණො", "⠵⠭");
        text = text.replace("ණෝ", "⠵⠕");
        text = text.replace("ණෙ", "⠵⠑");
        text = text.replace("ණේ", "⠵⠢");
        text = text.replace("ණෛ", "⠵⠑⠪");
        text = text.replace("ණු", "⠵⠥");
        text = text.replace("ණූ", "⠵⠳");
        text = text.replace("ණැ", "⠜⠷");
        text = text.replace("ණෑ", "⠜⠻");
        text = text.replace("ණෟ", "⠵⠳");
        text = text.replace("ණෞ", "⠵⠑⠥");
        text = text.replace("ණ", "⠵");
        //THA--
        text = text.replace("ත්", "⠈⠞");
        text = text.replace("තා", "⠞⠜");
        text = text.replace("ති", "⠞⠪");
        text = text.replace("තී", "⠞⠔");
        text = text.replace("තො", "⠞⠭");
        text = text.replace("තෝ", "⠞⠕");
        text = text.replace("තෙ", "⠞⠑");
        text = text.replace("තේ", "⠞⠢");
        text = text.replace("තෛ", "⠞⠑⠪");
        text = text.replace("තු", "⠞⠥");
        text = text.replace("තූ", "⠞⠳");
        text = text.replace("තැ", "⠜⠷");
        text = text.replace("තෑ", "⠜⠻");
        text = text.replace("තෟ", "⠞⠳");
        text = text.replace("ත්‍ර", "⠈⠞⠗");
        text = text.replace("තෞ", "⠞⠑⠥");
        text = text.replace("ත", "⠞");

        text = text.replace("ද්", "⠈⠙");
        text = text.replace("දා", "⠙⠜");
        text = text.replace("දි", "⠙⠪");
        text = text.replace("දී", "⠙⠔");
        text = text.replace("දො", "⠙⠭");
        text = text.replace("දෝ", "⠙⠕");
        text = text.replace("දෙ", "⠙⠑");
        text = text.replace("දේ", "⠙⠢");
        text = text.replace("දෛ", "⠙⠑⠪");
        text = text.replace("දු", "⠙⠥");
        text = text.replace("දූ", "⠙⠳");
        text = text.replace("දැ", "⠜⠷");
        text = text.replace("දෑ", "⠜⠻");
        //text = text.replace("⠙⠥", "⠙⠳");
        text = text.replace("ද්‍ර", "⠈⠙⠗");
        text = text.replace("දෞ", "⠙⠑⠥");
        text = text.replace("ද", "⠙");

        text = text.replace("ප්", "⠈⠏");
        text = text.replace("පා", "⠏⠜");
        text = text.replace("පි", "⠏⠪");
        text = text.replace("පී", "⠏⠔");
        text = text.replace("පො", "⠏⠭");
        text = text.replace("පෝ", "⠏⠕");
        text = text.replace("පෙ", "⠏⠑");
        text = text.replace("පේ", "⠏⠢");
        text = text.replace("පෛ", "⠏⠑⠪");
        text = text.replace("පු", "⠏⠥");
        text = text.replace("පූ", "⠏⠳");
        text = text.replace("පැ", "⠜⠷");
        text = text.replace("පෑ", "⠜⠻");
        text = text.replace("පෟ", "⠏⠳");
        text = text.replace("ප්‍ර", "⠈⠏⠗");
        text = text.replace("පෞ", "⠏⠑⠥");
        text = text.replace("ප", "⠏");

        text = text.replace("බ්", "⠈⠃");
        text = text.replace("බා", "⠃⠜");
        text = text.replace("බි", "⠃⠪");
        text = text.replace("බී", "⠃⠔");
        text = text.replace("බො", "⠃⠭");
        text = text.replace("බෝ", "⠃⠕");
        text = text.replace("බෙ", "⠃⠑");
        text = text.replace("බේ", "⠃⠢");
        text = text.replace("බෛ", "⠃⠑⠪");
        text = text.replace("බු", "⠃⠥");
        text = text.replace("බූ", "⠃⠳");
        text = text.replace("බැ", "⠜⠷");
        text = text.replace("බෑ", "⠜⠻");
        text = text.replace("බෟ", "⠃⠳");
        text = text.replace("බ්‍ර", "⠈⠃⠗");
        text = text.replace("බෞ", "⠛⠃⠥");
        text = text.replace("බ", "⠃");

        text = text.replace("ම්", "⠈⠍");
        text = text.replace("මා", "⠍⠜");
        text = text.replace("මි", "⠍⠪");
        text = text.replace("මී", "⠍⠔");
        text = text.replace("මො", "⠍⠭");
        text = text.replace("මෝ", "⠍⠕");
        text = text.replace("මෙ", "⠍⠑");
        text = text.replace("මේ", "⠍⠢");
        text = text.replace("මෛ", "⠍⠑⠪");
        text = text.replace("මු", "⠍⠥");
        text = text.replace("මූ", "⠍⠳");
        text = text.replace("මැ", "⠜⠷");
        text = text.replace("මෑ", "⠜⠻");
        text = text.replace("මෟ", "⠍⠳");
        text = text.replace("ම්‍ර", "⠈⠍⠗");
        text = text.replace("මෞ", "⠛⠍⠥");
        text = text.replace("ම", "⠍");


        text = text.replace("ෆා", "⠋⠜");
        text = text.replace("ෆි", "⠋⠪");
        text = text.replace("ෆී", "⠋⠔");
        text = text.replace("ෆො", "⠋⠭");
        text = text.replace("ෆෝ", "⠋⠕");
        text = text.replace("ෆෛ", "⠋⠑⠪");
        text = text.replace("ෆ්", "⠈⠋");
        text = text.replace("ෆ", "⠋");
        text = text.replace("ෆෙ", "⠋⠑");
        text = text.replace("ෆේ", "⠋⠢");
        text = text.replace("ෆු", "⠋⠥");
        text = text.replace("ෆූ", "⠽⠳");
        text = text.replace("ෆැ", "⠋⠷");
        text = text.replace("ෆෑ", "⠋⠻");
        text = text.replace("ෆෟ", "⠋⠳");

        text = text.replace("ය්", "⠈⠽");
        text = text.replace("යා", "⠽⠜");
        text = text.replace("යි", "⠽⠪");
        text = text.replace("යී", "⠽⠔");
        text = text.replace("යො", "⠽⠭");
        text = text.replace("යෝ", "⠽⠕");
        text = text.replace("යෙ", "⠽⠑");
        text = text.replace("යේ", "⠽⠢");
        text = text.replace("යෛ", "⠽⠑⠪");
        text = text.replace("යු", "⠽⠥");
        text = text.replace("යූ", "⠽⠳");
        text = text.replace("යැ", "⠜⠷");
        text = text.replace("යෑ", "⠜⠻");
        text = text.replace("යෟ", "⠽⠳");
        text = text.replace("ය්‍ර", "⠈⠽⠗");
        // text = text.replace("මෞ", "⠛⠍⠥");
        text = text.replace("ය", "⠽");

        text = text.replace("ල්", "⠈⠇");
        text = text.replace("ලා", "⠇⠜");
        text = text.replace("ලි", "⠇⠪");
        text = text.replace("ලී", "⠇⠔");
        text = text.replace("ලො", "⠇⠭");
        text = text.replace("ලෝ", "⠇⠕");
        text = text.replace("ලෙ", "⠇⠑");
        text = text.replace("ලේ", "⠇⠢");
        text = text.replace("ලෛ", "⠇⠑⠪");
        text = text.replace("ලු", "⠇⠥");
        text = text.replace("ලූ", "⠇⠳");
        text = text.replace("ලැ", "⠜⠷");
        text = text.replace("ලෑ", "⠜⠻");
        text = text.replace("ලෟ", "⠇⠳");
        text = text.replace("ලෞ", "⠇⠑⠥");
        text = text.replace("ල", "⠇");


        text = text.replace("ළ්", "⠈⠸");
        text = text.replace("ළා", "⠸⠜");
        text = text.replace("ළි", "⠸⠪");
        text = text.replace("ළී", "⠸⠔");
        text = text.replace("ළො", "⠸⠭");
        text = text.replace("ළෝ", "⠸⠕");
        text = text.replace("ළෙ", "⠸⠑");
        text = text.replace("ළේ", "⠸⠢");
        text = text.replace("ළෛ", "⠸⠑⠪");
        text = text.replace("ළැ", "⠸⠥");
        text = text.replace("ළෑ", "⠸⠳");
        text = text.replace("ළෟ", "⠜⠷");
        text = text.replace("ළ", "⠸");

        text = text.replace("ව්", "⠈⠧");
        text = text.replace("වා", "⠧⠜");
        text = text.replace("වි", "⠧⠪");
        text = text.replace("වී", "⠧⠔");
        text = text.replace("වො", "⠧⠭");
        text = text.replace("වෝ", "⠧⠕");
        text = text.replace("වෙ", "⠧⠑");
        text = text.replace("වේ", "⠧⠢");
        text = text.replace("වෛ", "⠧⠑⠪");
        text = text.replace("වු", "⠧⠥");
        text = text.replace("වූ", "⠧⠳");
        text = text.replace("වැ", "⠜⠷");
        text = text.replace("වෑ", "⠜⠻");
        text = text.replace("වෟ", "⠧⠳");
        text = text.replace("ව්‍ර", "⠈⠍⠗");
        text = text.replace("වෞ", "⠛⠍⠥");
        text = text.replace("ව", "⠧");

        text = text.replace("ෂ්", "⠈⠩");
        text = text.replace("ෂා", "⠩⠜");
        text = text.replace("ෂි", "⠩⠪");
        text = text.replace("ෂී", "⠩⠔");
        text = text.replace("ෂො", "⠩⠭");
        text = text.replace("ෂෝ", "⠩⠕");
        text = text.replace("ෂෙ", "⠩⠑");
        text = text.replace("ෂේ", "⠩⠢");
        text = text.replace("ෂෛ", "⠩⠑⠪");
        text = text.replace("ෂු", "⠩⠥");
        text = text.replace("ෂූ", "⠩⠳");
        text = text.replace("ෂැ", "⠜⠷");
        text = text.replace("ෂෑ", "⠜⠻");
        text = text.replace("ෂෟ", "⠩⠳");
        text = text.replace("ෂ", "⠩");

        text = text.replace("ස්", "⠈⠎");
        text = text.replace("සා", "⠎⠜");
        text = text.replace("සි", "⠎⠪");
        text = text.replace("සී", "⠎⠔");
        text = text.replace("සො", "⠎⠭");
        text = text.replace("සෝ", "⠎⠕");
        text = text.replace("සෙ", "⠎⠑");
        text = text.replace("සේ", "⠎⠢");
        text = text.replace("සෛ", "⠎⠑⠪");
        text = text.replace("සු", "⠎⠥");
        text = text.replace("සූ", "⠎⠳");
        text = text.replace("සැ", "⠜⠷");
        text = text.replace("සෑ", "⠜⠻");
        text = text.replace("සෟ", "⠎⠳");

        text = text.replace("ස", "⠎");

        text = text.replace("ශ්", "⠈⠯");
        text = text.replace("ශා", "⠯⠜");
        text = text.replace("ශි", "⠯⠪");
        text = text.replace("ශී", "⠯⠔");
        text = text.replace("ශො", "⠯⠭");
        text = text.replace("ශෝ", "⠯⠕");
        text = text.replace("ශෙ", "⠯⠑");
        text = text.replace("ශේ", "⠯⠢");
        text = text.replace("ශෛ", "⠯⠑⠪");
        text = text.replace("ශු", "⠯⠥");
        text = text.replace("ශූ", "⠯⠳");
        text = text.replace("ශැ", "⠜⠷");
        text = text.replace("ශෑ", "⠜⠻");
        text = text.replace("ශෟ", "⠯⠳");
        text = text.replace("ශ", "⠯");

        text = text.replace("ඞ්", "⠈⠟");
        text = text.replace("ඞා", "⠟⠜");
        text = text.replace("ඞි", "⠟⠪");
        text = text.replace("ඞී", "⠟⠔");
        text = text.replace("ඞො", "⠟⠭");
        text = text.replace("ඞෝ", "⠟⠕");
        text = text.replace("ඞෙ", "⠟⠑");
        text = text.replace("ඞේ", "⠟⠢");
        text = text.replace("ඞෛ", "⠟⠑⠪");
        text = text.replace("ඞු", "⠟⠥");
        text = text.replace("ඞූ", "⠟⠳");
        text = text.replace("ඞැ", "⠜⠷");
        text = text.replace("ඞෑ", "⠜⠻");
        text = text.replace("ඞෟ", "⠟⠳");

        text = text.replace("ඞ", "⠟");

        text = text.replace("ඥ්", "⠈⠟");
        text = text.replace("ඥ", "⠟");
        text = text.replace("ඥා", "⠟⠜");
        text = text.replace("ඥි", "⠟⠪");
        text = text.replace("ඥී", "⠟⠔");
        text = text.replace("ඥො", "⠟⠭");
        text = text.replace("ඥෝ", "⠟⠕");
        text = text.replace("ඥෙ", "⠟⠑");
        text = text.replace("ඥේ", "⠟⠢");
        text = text.replace("ඥෛ", "⠟⠑⠪");
        text = text.replace("ඥු", "⠟⠥");
        text = text.replace("ඥූ", "⠟⠳");
        text = text.replace("ඥැ", "⠜⠷");
        text = text.replace("ඥෑ", "⠜⠻");
        text = text.replace("ඥෟ", "⠟⠳");
        // text = text.replace("ඥෞ", "ඥෞ");

        text = text.replace("ඤ්", "⠈⠒");
        text = text.replace("ඤ", "⠒");
        text = text.replace("ඤා", "⠒⠜");
        text = text.replace("ඤි", "⠒⠜");
        text = text.replace("ඤී", "⠒⠔");
        text = text.replace("ඤො", "⠒⠭");
        text = text.replace("ඤෝ", "⠒⠕");
        text = text.replace("ඤෙ", "⠒⠑");
        text = text.replace("ඤේ", "⠒⠢");
        text = text.replace("ඤෛ", "⠒⠑⠪");
        text = text.replace("ඤු", "⠒⠥");
        text = text.replace("ඤූ", "⠒⠥");
        text = text.replace("ඤැ", "⠜⠷");
        text = text.replace("ඤෑ", "⠜⠻");
        text = text.replace("ඤෟ", "⠒⠳");
        // text = text.replace("ඤෞ", "ඤෞ");

        text = text.replace("ජ්ඤ්", "ඥ්");
        text = text.replace("ග්න්", "ඥ්");
        text = text.replace("ඤ්ජ්", "ඦ්");
        text = text.replace("ණ්ඩ්", "ඬ්");

        text = text.replace("ඳ්", "⠈⠙");
        text = text.replace("ඳා", "⠙⠜");
        text = text.replace("ඳි", "⠙⠪");
        text = text.replace("ඳී", "⠙⠔");
        text = text.replace("ඳො", "⠙⠭");
        text = text.replace("දෝ", "⠙⠕");
        text = text.replace("ඳෙ", "⠙⠑");
        text = text.replace("ඳේ", "⠙⠢");
        text = text.replace("ඳෛ", "⠙⠑⠪");
        text = text.replace("ඳු", "⠙⠥");
        text = text.replace("ඳූ", "⠙⠳");
        text = text.replace("ඳැ", "⠜⠷");
        text = text.replace("ඳ්ෑ", "⠜⠻");
        text = text.replace("⠙⠥", "⠙⠳");

        text = text.replace("ඳ", "⠙");

        text = text.replace("ඹ්", "⠈⠕");
        text = text.replace("ඹා", "⠕⠜");
        text = text.replace("ඹි", "⠕⠪");
        text = text.replace("⠕⠪⠪", "⠕⠔");
        text = text.replace("ඹො", "⠕⠭");
        text = text.replace("ඹෝ", "⠕⠕");
        text = text.replace("ඹෙ", "⠕⠑");
        text = text.replace("ඹේ", "⠕⠢");
        text = text.replace("ඹෛ", "⠕⠑⠪");
        text = text.replace("ඹු", "⠕⠥");
        text = text.replace("ඹූ", "⠕⠳");
        text = text.replace("ඹැ", "⠜⠷");
        text = text.replace("ඹෑ", "⠜⠻");
        text = text.replace("⠕⠥", "⠕⠳");
        text = text.replace("ඹ", "⠕");

        text = text.replace("ඣ්", "⠈⠴");
        text = text.replace("ඣා", "⠴⠜");
        text = text.replace("ඣි", "⠴⠪");
        text = text.replace("ඣී", "⠴⠔");
        text = text.replace("ඣො", "⠴⠭");
        text = text.replace("ඣෝ", "⠴⠴");
        text = text.replace("ඣෙ", "⠴⠑");
        text = text.replace("ඣේ", "⠴⠢");
        text = text.replace("ඣෛ", "⠴⠑⠪");
        text = text.replace("ඣු", "⠴⠥");
        text = text.replace("ඣූ", "⠴⠳");
        text = text.replace("ඣැ", "⠜⠷");
        text = text.replace("ඣෑ", "⠜⠻");
        // text = text.replace("⠴⠥", "⠴⠳");

        text = text.replace("ඣ", "⠴");

        text = text.replace("ඨ්", "⠈⠺");
        text = text.replace("ඨා", "⠺⠜");
        text = text.replace("ඨි", "⠺⠪");
        text = text.replace("ඨී", "⠺⠔");
        text = text.replace("ඨො", "⠺⠭");
        text = text.replace("ඨෝ", "⠺⠺");
        text = text.replace("ඨෙ", "⠺⠑");
        text = text.replace("ඨේ", "⠺⠢");
        text = text.replace("ඨෛ", "⠺⠑⠪");
        text = text.replace("ඨු", "⠺⠥");
        text = text.replace("ඨූ", "⠺⠳");
        text = text.replace("ඨැ", "⠜⠷");
        text = text.replace("ඨෑ", "⠜⠻");
        // text = text.replace("⠺⠥", "⠺⠳");
        text = text.replace("ඨ", "⠺");

        text = text.replace("ඪ්", "⠈⠿");
        text = text.replace("ඪා", "⠿⠜");
        text = text.replace("ඪි", "⠿⠪");
        text = text.replace("ඪී", "⠿⠔");
        text = text.replace("ඪො", "⠿⠭");
        text = text.replace("ඪෝ", "⠿⠿");
        text = text.replace("ඪෙ", "⠿⠑");
        text = text.replace("ඪේ", "⠿⠢");
        text = text.replace("ඪෛ", "⠿⠑⠪");
        text = text.replace("ඪු", "⠿⠥");
        text = text.replace("ඪූ", "⠿⠳");
        text = text.replace("ඪැ", "⠜⠷");
        text = text.replace("ඪෑ", "⠜⠻");
        //text = text.replace("⠿⠥", "⠿⠳");
        text = text.replace("ඪ", "⠿");

        text = text.replace("ථ්", "⠈⠹");
        text = text.replace("ථා", "⠹⠜");
        text = text.replace("ථි", "⠹⠪");
        text = text.replace("ථී", "⠹⠔");
        text = text.replace("ථො", "⠹⠭");
        text = text.replace("ථෝ", "⠹⠹");
        text = text.replace("ථෙ", "⠹⠑");
        text = text.replace("ථේ", "⠹⠢");
        text = text.replace("ථෛ", "⠹⠑⠪");
        text = text.replace("ථු", "⠹⠥");
        text = text.replace("ථූ", "⠹⠳");
        text = text.replace("ථැ", "⠜⠷");
        text = text.replace("ථෑ", "⠜⠻");
        // text = text.replace("⠹⠥", "⠹⠳");
        text = text.replace("ථ", "⠹");
        text = text.replace("ද්හ්", "ධ්");
        //text = text.replace("ථ්අ", "ථ");
        //text = text.replace("ථඅ", "ථා");
        //text = text.replace("ථ්ඉ", "ථි");
        //text = text.replace("ථිඉ", "ථී");
        //text = text.replace("ථ්ඔ", "ථො");
        //text = text.replace("ථොඔ", "ථෝ");
        //text = text.replace("ථ්එ", "ථෙ");
        //text = text.replace("ථෙඑ", "ථේ");
        //text = text.replace("ථේඉ", "ථෛ");
        //text = text.replace("ථඋ", "ථු");
        //text = text.replace("ථුඋ", "ථූ");
        //text = text.replace("ථ්A", "ථැ");
        //text = text.replace("ථැඅ", "ථෑ");
        text = text.replace("ඵ්", "⠈⠱");
        text = text.replace("ඵා", "⠱⠜");
        text = text.replace("ඵි", "⠱⠪");
        text = text.replace("ඵී", "⠱⠔");
        text = text.replace("ඵො", "⠱⠭");
        text = text.replace("ඵෝ", "⠱⠱");
        text = text.replace("ඵෙ", "⠱⠑");
        text = text.replace("ථේ", "⠱⠢");
        text = text.replace("ඵෛ", "⠱⠑⠪");
        text = text.replace("ඵු", "⠱⠥");
        text = text.replace("ඵූ", "⠱⠳");
        text = text.replace("ඵැ", "⠜⠷");
        text = text.replace("ඵෑ", "⠜⠻");
        //text = text.replace("⠱⠥", "⠱⠳");
        text = text.replace("ඵ", "⠱");

        text = text.replace("භ්", "⠈⠘");
        text = text.replace("භා", "⠘⠜");
        text = text.replace("භි", "⠘⠪");
        text = text.replace("භී", "⠘⠔");
        text = text.replace("භො", "⠘⠭");
        text = text.replace("භෝ", "⠘⠘");
        text = text.replace("භෙ", "⠘⠑");
        text = text.replace("භේ", "⠘⠢");
        text = text.replace("භෛ", "⠘⠑⠪");
        text = text.replace("භු", "⠘⠥");
        text = text.replace("භූ", "⠘⠳");
        text = text.replace("භැ", "⠜⠷");
        text = text.replace("භෑ", "⠜⠻");
        // text = text.replace("⠘⠥", "⠘⠳");
        text = text.replace("භ", "⠘");

        text = text.replace("ඏඉ", "ඐ");
        //*******************************************************
        text = text.replace("a", "⠁");
        text = text.replace("⠁⠁", "⠜");
        text = text.replace("i", "⠪");
        text = text.replace("⠪⠪", "⠔");
        text = text.replace("u", "⠥");
        text = text.replace("⠥⠥", "⠳");
        text = text.replace("e", "⠑");
        text = text.replace("⠑⠑", "⠢");
        text = text.replace("o", "⠭");
        text = text.replace("⠭⠭", "⠕");
        text = text.replace("⠁A", "⠷");
        text = text.replace("⠷⠁", "⠻");
        text = text.replace("⠁⠪", "⠈");
        text = text.replace("⠁⠥", "⠌");

        text = text.replace("r", "⠈⠗");
        text = text.replace("⠈⠗⠁", "⠗");
        text = text.replace("⠗⠁", "⠗⠜");
        text = text.replace("⠈⠗⠪", "⠗⠪");
        text = text.replace("⠗⠪⠪", "⠗⠔");
        text = text.replace("⠈⠗⠭", "⠗⠭");
        text = text.replace("⠗⠭⠭", "⠗⠕");
        text = text.replace("⠈⠗⠑", "⠗⠑");
        text = text.replace("⠗⠑⠑", "⠗⠢");
        text = text.replace("⠗⠢⠪", "⠗⠑⠪");
        text = text.replace("⠈⠗⠈⠗", "⠗⠥");
        text = text.replace("⠗⠥⠥", "⠗⠳");
        text = text.replace("⠗⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠗⠥", "⠗⠳");

        //cons
        text = text.replace("n", "⠈⠝");
        text = text.replace("⠈⠝⠁", "⠝");
        text = text.replace("⠝⠁", "⠝⠜");
        text = text.replace("⠈⠝⠪", "⠝⠪");
        text = text.replace("⠝⠪⠪", "⠝⠔");
        text = text.replace("⠈⠝⠭", "⠝⠭");
        text = text.replace("⠝⠭⠭", "⠝⠕");
        text = text.replace("⠈⠝⠑", "⠝⠑");
        text = text.replace("⠝⠑⠑", "⠝⠢");
        text = text.replace("⠝⠢⠪", "⠝⠑⠪");
        text = text.replace("⠈⠝⠈⠝", "⠝⠥");
        text = text.replace("⠝⠥⠥", "⠝⠳");
        text = text.replace("⠝⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠝⠥", "⠝⠳");

        text = text.replace("⠈⠝'", "⠈⠝");

        text = text.replace("h", "⠈⠓");
        text = text.replace("⠈⠓⠁", "⠓");
        text = text.replace("⠓⠁", "⠓⠜");
        text = text.replace("⠈⠓⠪", "⠓⠪");
        text = text.replace("⠓⠪⠪", "⠓⠔");
        text = text.replace("⠈⠓⠭", "⠓⠭");
        text = text.replace("⠓⠭⠭", "⠓⠕");
        text = text.replace("⠈⠓⠑", "⠓⠑");
        text = text.replace("⠓⠑⠑", "⠓⠢");
        text = text.replace("⠓⠢⠪", "⠓⠑⠪");
        text = text.replace("⠈⠓⠈⠓", "⠓⠥");
        text = text.replace("⠓⠥⠥", "⠓⠳");
        text = text.replace("⠓⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠓⠥", "⠓⠳");

        text = text.replace("අහ්", "අං");
        text = text.replace("අන්", "අඃ");

        text = text.replace("k", "⠈⠅");
        text = text.replace("⠈⠅⠁", "⠅");
        text = text.replace("⠅⠁", "⠅⠜");
        text = text.replace("⠈⠅⠪", "⠅⠪");
        text = text.replace("⠅⠪⠪", "⠅⠔");
        text = text.replace("⠈⠅⠭", "⠅⠭");
        text = text.replace("⠅⠭⠭", "⠅⠕");
        text = text.replace("⠈⠅⠑", "⠅⠑");
        text = text.replace("⠅⠑⠑", "⠅⠢");
        text = text.replace("⠅⠢⠪", "⠅⠑⠪");
        text = text.replace("⠈⠅⠈⠅", "⠅⠥");
        text = text.replace("⠅⠥⠥", "⠅⠳");
        text = text.replace("⠅⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠅⠥", "⠅⠳");


        text = text.replace("g", "⠈⠛");
        text = text.replace("⠈⠛⠁", "⠛");
        text = text.replace("⠛⠁", "⠛⠜");
        text = text.replace("⠈⠛⠪", "⠛⠪");
        text = text.replace("⠛⠪⠪", "⠛⠔");
        text = text.replace("⠈⠛⠭", "⠛⠭");
        text = text.replace("⠛⠭⠭", "⠛⠕");
        text = text.replace("⠈⠛⠑", "⠛⠑");
        text = text.replace("⠛⠑⠑", "⠛⠢");
        text = text.replace("⠛⠢⠪", "⠛⠑⠪");
        text = text.replace("⠈⠛⠈⠛", "⠛⠥");
        text = text.replace("⠛⠥⠥", "⠛⠳");
        text = text.replace("⠛⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠛⠥", "⠛⠳");

        text = text.replace("c⠈⠓", "⠈⠉");
        text = text.replace("⠈⠉⠁", "⠉");
        text = text.replace("⠉⠁", "⠉⠜");
        text = text.replace("⠈⠉⠪", "⠉⠪");
        text = text.replace("⠉⠪⠪", "⠉⠔");
        text = text.replace("⠈⠉⠭", "⠉⠭");
        text = text.replace("⠉⠭⠭", "⠉⠕");
        text = text.replace("⠈⠉⠑", "⠉⠑");
        text = text.replace("⠉⠑⠑", "⠉⠢");
        text = text.replace("⠉⠢⠪", "⠉⠑⠪");
        text = text.replace("⠈⠉⠈⠉", "⠉⠥");
        text = text.replace("⠉⠥⠥", "⠉⠳");
        text = text.replace("⠉⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠉⠥", "⠉⠳");

        text = text.replace("j", "⠈⠡");
        text = text.replace("⠈⠡⠁", "⠡");
        text = text.replace("⠡⠁", "⠡⠜");
        text = text.replace("⠈⠡⠪", "⠡⠪");
        text = text.replace("⠡⠪⠪", "⠡⠔");
        text = text.replace("⠈⠡⠭", "⠡⠭");
        text = text.replace("⠡⠭⠭", "⠡⠕");
        text = text.replace("⠈⠡⠑", "⠡⠑");
        text = text.replace("⠡⠑⠑", "⠡⠢");
        text = text.replace("⠡⠢⠪", "⠡⠑⠪");
        text = text.replace("⠈⠡⠈⠡", "⠡⠥");
        text = text.replace("⠡⠥⠥", "⠡⠳");
        text = text.replace("⠡⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠡⠥", "⠡⠳");

        text = text.replace("t", "⠈⠾");
        text = text.replace("⠈⠾⠁", "⠾");
        text = text.replace("⠾⠁", "⠾⠜");
        text = text.replace("⠈⠾⠪", "⠾⠪");
        text = text.replace("⠾⠪⠪", "⠾⠔");
        text = text.replace("⠈⠾⠭", "⠾⠭");
        text = text.replace("⠾⠭⠭", "⠾⠕");
        text = text.replace("⠈⠾⠑", "⠾⠑");
        text = text.replace("⠾⠑⠑", "⠾⠢");
        text = text.replace("⠾⠢⠪", "⠾⠑⠪");
        text = text.replace("⠈⠾⠈⠾", "⠾⠥");
        text = text.replace("⠾⠥⠥", "⠾⠳");
        text = text.replace("⠾⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠾⠥", "⠾⠳");

        text = text.replace("d", "⠈⠫");
        text = text.replace("⠈⠫⠁", "⠫");
        text = text.replace("⠫⠁", "⠫⠜");
        text = text.replace("⠈⠫⠪", "⠫⠪");
        text = text.replace("⠫⠪⠪", "⠫⠔");
        text = text.replace("⠈⠫⠭", "⠫⠭");
        text = text.replace("⠫⠭⠭", "⠫⠕");
        text = text.replace("⠈⠫⠑", "⠫⠑");
        text = text.replace("⠫⠑⠑", "⠫⠢");
        text = text.replace("⠫⠢⠪", "⠫⠑⠪");
        text = text.replace("⠈⠫⠈⠫", "⠫⠥");
        text = text.replace("⠫⠥⠥", "⠫⠳");
        text = text.replace("⠫⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠫⠥", "⠫⠳");

        text = text.replace("N", "⠈⠵");
        text = text.replace("⠈⠵⠁", "⠵");
        text = text.replace("⠵⠁", "⠵⠜");
        text = text.replace("⠈⠵⠪", "⠵⠪");
        text = text.replace("⠵⠪⠪", "⠵⠔");
        text = text.replace("⠈⠵⠭", "⠵⠭");
        text = text.replace("⠵⠭⠭", "⠵⠕");
        text = text.replace("⠈⠵⠑", "⠵⠑");
        text = text.replace("⠵⠑⠑", "⠵⠢");
        text = text.replace("⠵⠢⠪", "⠵⠑⠪");
        text = text.replace("⠈⠵⠈⠵", "⠵⠥");
        text = text.replace("⠵⠥⠥", "⠵⠳");
        text = text.replace("⠵⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠵⠥", "⠵⠳");

        //THA--
        text = text.replace("⠈⠾⠈⠓", "⠈⠞");
        text = text.replace("⠈⠞⠁", "⠞");
        text = text.replace("⠞⠁", "⠞⠜");
        text = text.replace("⠈⠞⠪", "⠞⠪");
        text = text.replace("⠞⠪⠪", "⠞⠔");
        text = text.replace("⠈⠞⠭", "⠞⠭");
        text = text.replace("⠞⠭⠭", "⠞⠕");
        text = text.replace("⠈⠞⠑", "⠞⠑");
        text = text.replace("⠞⠑⠑", "⠞⠢");
        text = text.replace("⠞⠢⠪", "⠞⠑⠪");
        text = text.replace("⠈⠞⠈⠞", "⠞⠥");
        text = text.replace("⠞⠥⠥", "⠞⠳");
        text = text.replace("⠞⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠞⠥", "⠞⠳");

        text = text.replace("⠈⠫⠈⠓", "⠈⠙");
        text = text.replace("⠈⠙⠁", "⠙");
        text = text.replace("⠙⠁", "⠙⠜");
        text = text.replace("⠈⠙⠪", "⠙⠪");
        text = text.replace("⠙⠪⠪", "⠙⠔");
        text = text.replace("⠈⠙⠭", "⠙⠭");
        text = text.replace("⠙⠭⠭", "⠙⠕");
        text = text.replace("⠈⠙⠑", "⠙⠑");
        text = text.replace("⠙⠑⠑", "⠙⠢");
        text = text.replace("⠙⠢⠪", "⠙⠑⠪");
        text = text.replace("⠈⠙⠈⠙", "⠙⠥");
        text = text.replace("⠙⠥⠥", "⠙⠳");
        text = text.replace("⠙⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠙⠥", "⠙⠳");

        text = text.replace("p", "⠈⠏");
        text = text.replace("⠈⠏⠁", "⠏");
        text = text.replace("⠏⠁", "⠏⠜");
        text = text.replace("⠈⠏⠪", "⠏⠪");
        text = text.replace("⠏⠪⠪", "⠏⠔");
        text = text.replace("⠈⠏⠭", "⠏⠭");
        text = text.replace("⠏⠭⠭", "⠏⠕");
        text = text.replace("⠈⠏⠑", "⠏⠑");
        text = text.replace("⠏⠑⠑", "⠏⠢");
        text = text.replace("⠏⠢⠪", "⠏⠑⠪");
        text = text.replace("⠈⠏⠈⠏", "⠏⠥");
        text = text.replace("⠏⠥⠥", "⠏⠳");
        text = text.replace("⠏⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠏⠥", "⠏⠳");

        text = text.replace("b", "⠈⠃");
        text = text.replace("⠈⠃⠁", "⠃");
        text = text.replace("⠃⠁", "⠃⠜");
        text = text.replace("⠈⠃⠪", "⠃⠪");
        text = text.replace("⠃⠪⠪", "⠃⠔");
        text = text.replace("⠈⠃⠭", "⠃⠭");
        text = text.replace("⠃⠭⠭", "⠃⠕");
        text = text.replace("⠈⠃⠑", "⠃⠑");
        text = text.replace("⠃⠑⠑", "⠃⠢");
        text = text.replace("⠃⠢⠪", "⠃⠑⠪");
        text = text.replace("⠈⠃⠈⠃", "⠃⠥");
        text = text.replace("⠃⠥⠥", "⠃⠳");
        text = text.replace("⠃⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠃⠥", "⠃⠳");

        text = text.replace("m", "⠈⠍");
        text = text.replace("⠈⠍⠁", "⠍");
        text = text.replace("⠍⠁", "⠍⠜");
        text = text.replace("⠈⠍⠪", "⠍⠪");
        text = text.replace("⠍⠪⠪", "⠍⠔");
        text = text.replace("⠈⠍⠭", "⠍⠭");
        text = text.replace("⠍⠭⠭", "⠍⠕");
        text = text.replace("⠈⠍⠑", "⠍⠑");
        text = text.replace("⠍⠑⠑", "⠍⠢");
        text = text.replace("⠍⠢⠪", "⠍⠑⠪");
        text = text.replace("⠍⠥", "⠍⠥");
        text = text.replace("⠥⠥", "⠍⠳");
        text = text.replace("⠍⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠍⠥", "⠍⠳");

        text = text.replace("y", "⠈⠽");
        text = text.replace("⠈⠽⠁", "⠽");
        text = text.replace("⠽⠁", "⠽⠜");
        text = text.replace("⠈⠽⠪", "⠽⠪");
        text = text.replace("⠽⠪⠪", "⠽⠔");
        text = text.replace("⠈⠽⠭", "⠽⠭");
        text = text.replace("⠽⠭⠭", "⠽⠕");
        text = text.replace("⠈⠽⠑", "⠽⠑");
        text = text.replace("⠽⠑⠑", "⠽⠢");
        text = text.replace("⠽⠢⠪", "⠽⠑⠪");
        text = text.replace("⠈⠽⠈⠽", "⠽⠥");
        text = text.replace("⠽⠥⠥", "⠽⠳");
        text = text.replace("⠽⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠽⠥", "⠽⠳");

        text = text.replace("l", "⠈⠇");
        text = text.replace("⠈⠇⠁", "⠇");
        text = text.replace("⠇⠁", "⠇⠜");
        text = text.replace("⠈⠇⠪", "⠇⠪");
        text = text.replace("⠇⠪⠪", "⠇⠔");
        text = text.replace("⠈⠇⠭", "⠇⠭");
        text = text.replace("⠇⠭⠭", "⠇⠕");
        text = text.replace("⠈⠇⠑", "⠇⠑");
        text = text.replace("⠇⠑⠑", "⠇⠢");
        text = text.replace("⠇⠢⠪", "⠇⠑⠪");
        text = text.replace("⠈⠇⠈⠇", "⠇⠥");
        text = text.replace("⠇⠥⠥", "⠇⠳");
        text = text.replace("⠇⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠇⠥", "⠇⠳");

        text = text.replace("L", "⠈⠸");
        text = text.replace("⠈⠸⠁", "⠸");
        text = text.replace("⠸⠁", "⠸⠜");
        text = text.replace("⠈⠸⠪", "⠸⠪");
        text = text.replace("⠸⠪⠪", "⠸⠔");
        text = text.replace("⠈⠸⠭", "⠸⠭");
        text = text.replace("⠸⠭⠭", "⠸⠕");
        text = text.replace("⠈⠸⠑", "⠸⠑");
        text = text.replace("⠸⠑⠑", "⠸⠢");
        text = text.replace("⠸⠢⠪", "⠸⠑⠪");
        text = text.replace("⠈⠸⠈⠸", "⠸⠥");
        text = text.replace("⠸⠥⠥", "⠸⠳");
        text = text.replace("⠸⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠸⠥", "⠸⠳");

        text = text.replace("v", "⠈⠧");
        text = text.replace("⠈⠧⠁", "⠧");
        text = text.replace("⠧⠁", "⠧⠜");
        text = text.replace("⠈⠧⠪", "⠧⠪");
        text = text.replace("⠧⠪⠪", "⠧⠔");
        text = text.replace("⠈⠧⠭", "⠧⠭");
        text = text.replace("⠧⠭⠭", "⠧⠕");
        text = text.replace("⠈⠧⠑", "⠧⠑");
        text = text.replace("⠧⠑⠑", "⠧⠢");
        text = text.replace("⠧⠢⠪", "⠧⠑⠪");
        text = text.replace("⠈⠧⠈⠧", "⠧⠥");
        text = text.replace("⠧⠥⠥", "⠧⠳");
        text = text.replace("⠧⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠧⠥", "⠧⠳");

        text = text.replace("S", "⠈⠩");
        text = text.replace("⠈⠩⠁", "⠩");
        text = text.replace("⠩⠁", "⠩⠜");
        text = text.replace("⠈⠩⠪", "⠩⠪");
        text = text.replace("⠩⠪⠪", "⠩⠔");
        text = text.replace("⠈⠩⠭", "⠩⠭");
        text = text.replace("⠩⠭⠭", "⠩⠕");
        text = text.replace("⠈⠩⠑", "⠩⠑");
        text = text.replace("⠩⠑⠑", "⠩⠢");
        text = text.replace("⠩⠢⠪", "⠩⠑⠪");
        text = text.replace("⠈⠩⠈⠩", "⠩⠥");
        text = text.replace("⠩⠥⠥", "⠩⠳");
        text = text.replace("⠩⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠩⠥", "⠩⠳");

        text = text.replace("s", "⠈⠎");
        text = text.replace("⠈⠎⠁", "⠎");
        text = text.replace("⠎⠁", "⠎⠜");
        text = text.replace("⠈⠎⠪", "⠎⠪");
        text = text.replace("⠎⠪⠪", "⠎⠔");
        text = text.replace("⠈⠎⠭", "⠎⠭");
        text = text.replace("⠎⠭⠭", "⠎⠕");
        text = text.replace("⠈⠎⠑", "⠎⠑");
        text = text.replace("⠎⠑⠑", "⠎⠢");
        text = text.replace("⠎⠢⠪", "⠎⠑⠪");
        text = text.replace("⠈⠎⠈⠎", "⠎⠥");
        text = text.replace("⠎⠥⠥", "⠎⠳");
        text = text.replace("⠎⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠎⠥", "⠎⠳");

        text = text.replace("⠈⠎⠈⠓", "⠈⠯");
        text = text.replace("⠈⠯⠁", "⠯");
        text = text.replace("⠯⠁", "⠯⠜");
        text = text.replace("⠈⠯⠪", "⠯⠪");
        text = text.replace("⠯⠪⠪", "⠯⠔");
        text = text.replace("⠈⠯⠭", "⠯⠭");
        text = text.replace("⠯⠭⠭", "⠯⠕");
        text = text.replace("⠈⠯⠑", "⠯⠑");
        text = text.replace("⠯⠑⠑", "⠯⠢");
        text = text.replace("⠯⠢⠪", "⠯⠑⠪");
        text = text.replace("⠈⠯⠈⠯", "⠯⠥");
        text = text.replace("⠯⠥⠥", "⠯⠳");
        text = text.replace("⠯⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠯⠥", "⠯⠳");

        text = text.replace("⠈⠝⠈⠫", "⠈⠟");
        text = text.replace("⠈⠟⠁", "⠟");
        text = text.replace("⠟⠁", "⠟⠜");
        text = text.replace("⠈⠟⠪", "⠟⠪");
        text = text.replace("⠟⠪⠪", "⠟⠔");
        text = text.replace("⠈⠟⠭", "⠟⠭");
        text = text.replace("⠟⠭⠭", "⠟⠕");
        text = text.replace("⠈⠟⠑", "⠟⠑");
        text = text.replace("⠟⠑⠑", "⠟⠢");
        text = text.replace("⠟⠢⠪", "⠟⠑⠪");
        text = text.replace("⠈⠟⠈⠟", "⠟⠥");
        text = text.replace("⠟⠥⠥", "⠟⠳");
        text = text.replace("⠟⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠟⠥", "⠟⠳");

        text = text.replace("KN", "⠈⠒");
        text = text.replace("⠈⠒⠁", "⠒");
        text = text.replace("⠒⠁", "⠒⠜");
        text = text.replace("⠈⠒⠪", "⠒⠜");
        text = text.replace("⠒⠪⠪", "⠒⠔");
        text = text.replace("⠈⠒⠭", "⠒⠭");
        text = text.replace("⠒⠭⠭", "⠒⠕");
        text = text.replace("⠈⠒⠑", "⠒⠑");
        text = text.replace("⠒⠑⠑", "⠒⠢");
        text = text.replace("⠒⠢⠪", "⠒⠑⠪");
        text = text.replace("⠈⠒⠈⠒", "⠒⠥");
        text = text.replace("⠒⠥⠥", "⠒⠳");
        text = text.replace("⠒⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠒⠥", "⠒⠳");

        text = text.replace("GN", "⠈⠟");
        text = text.replace("⠈⠟⠁", "⠟");
        text = text.replace("⠟⠁", "⠟⠜");
        text = text.replace("⠈⠟⠪", "⠟⠪");
        text = text.replace("⠟⠪⠪", "⠟⠔");
        text = text.replace("⠈⠟⠭", "⠟⠭");
        text = text.replace("⠟⠭⠭", "⠟⠕");
        text = text.replace("⠈⠟⠑", "⠟⠑");
        text = text.replace("⠟⠑⠑", "⠟⠢");
        text = text.replace("⠟⠢⠪", "⠟⠑⠪");
        text = text.replace("⠈⠟⠈⠟", "⠟⠥");
        text = text.replace("⠟⠥⠥", "⠟⠳");
        text = text.replace("⠟⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠟⠥", "⠟⠳");
        text = text.replace("ඤ්ජ්", "ඦ්");
        text = text.replace("ණ්ඩ්", "ඬ්");

        text = text.replace("⠈⠝⠈⠙", "⠈⠙");
        text = text.replace("⠈⠙⠁", "⠙");
        text = text.replace("⠙⠁", "⠙⠜");
        text = text.replace("⠈⠙⠪", "⠙⠪");
        text = text.replace("⠙⠪⠪", "⠙⠔");
        text = text.replace("⠈⠙⠭", "⠙⠭");
        text = text.replace("⠙⠭⠭", "⠙⠕");
        text = text.replace("⠈⠙⠑", "⠙⠑");
        text = text.replace("⠙⠑⠑", "⠙⠢");
        text = text.replace("⠙⠢⠪", "⠙⠑⠪");
        text = text.replace("⠈⠙⠈⠙", "⠙⠥");
        text = text.replace("⠙⠥⠥", "⠙⠳");
        text = text.replace("⠙⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠙⠥", "⠙⠳");

        text = text.replace("⠈⠍⠈⠃", "⠈⠕");
        text = text.replace("⠈⠕⠁", "⠕");
        text = text.replace("⠕⠁", "⠕⠜");
        text = text.replace("⠈⠕⠪", "⠕⠪");
        text = text.replace("⠕⠪⠪", "⠕⠔");
        text = text.replace("⠈⠕⠭", "⠕⠭");
        text = text.replace("⠕⠭⠭", "⠕⠕");
        text = text.replace("⠈⠕⠑", "⠕⠑");
        text = text.replace("⠕⠑⠑", "⠕⠢");
        text = text.replace("⠕⠢⠪", "⠕⠑⠪");
        text = text.replace("⠈⠕⠈⠕", "⠕⠥");
        text = text.replace("⠕⠥⠥", "⠕⠳");
        text = text.replace("⠕⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠕⠥", "⠕⠳");

        text = text.replace("⠈⠡⠈⠓", "⠈⠴");
        text = text.replace("⠈⠴⠁", "⠴");
        text = text.replace("⠴⠁", "⠴⠜");
        text = text.replace("⠈⠴⠪", "⠴⠪");
        text = text.replace("⠴⠪⠪", "⠴⠔");
        text = text.replace("⠈⠴⠭", "⠴⠭");
        text = text.replace("⠴⠭⠭", "⠴⠴");
        text = text.replace("⠈⠴⠑", "⠴⠑");
        text = text.replace("⠴⠑⠑", "⠴⠢");
        text = text.replace("⠴⠢⠪", "⠴⠑⠪");
        text = text.replace("⠈⠴⠈⠴", "⠴⠥");
        text = text.replace("⠴⠥⠥", "⠴⠳");
        text = text.replace("⠴⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠴⠥", "⠴⠳");

        text = text.replace("⠈⠾⠈⠓", "⠈⠺");
        text = text.replace("⠈⠺⠁", "⠺");
        text = text.replace("⠺⠁", "⠺⠜");
        text = text.replace("⠈⠺⠪", "⠺⠪");
        text = text.replace("⠺⠪⠪", "⠺⠔");
        text = text.replace("⠈⠺⠭", "⠺⠭");
        text = text.replace("⠺⠭⠭", "⠺⠺");
        text = text.replace("⠈⠺⠑", "⠺⠑");
        text = text.replace("⠺⠑⠑", "⠺⠢");
        text = text.replace("⠺⠢⠪", "⠺⠑⠪");
        text = text.replace("⠈⠺⠈⠺", "⠺⠥");
        text = text.replace("⠺⠥⠥", "⠺⠳");
        text = text.replace("⠺⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠺⠥", "⠺⠳");

        text = text.replace("⠈⠫⠈⠓", "⠈⠿");
        text = text.replace("⠈⠿⠁", "⠿");
        text = text.replace("⠿⠁", "⠿⠜");
        text = text.replace("⠈⠿⠪", "⠿⠪");
        text = text.replace("⠿⠪⠪", "⠿⠔");
        text = text.replace("⠈⠿⠭", "⠿⠭");
        text = text.replace("⠿⠭⠭", "⠿⠿");
        text = text.replace("⠈⠿⠑", "⠿⠑");
        text = text.replace("⠿⠑⠑", "⠿⠢");
        text = text.replace("⠿⠢⠪", "⠿⠑⠪");
        text = text.replace("⠈⠿⠈⠿", "⠿⠥");
        text = text.replace("⠿⠥⠥", "⠿⠳");
        text = text.replace("⠿⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠿⠥", "⠿⠳");

        text = text.replace("⠈⠞⠈⠓", "⠈⠹");
        text = text.replace("⠈⠹⠁", "⠹");
        text = text.replace("⠹⠁", "⠹⠜");
        text = text.replace("⠈⠹⠪", "⠹⠪");
        text = text.replace("⠹⠪⠪", "⠹⠔");
        text = text.replace("⠈⠹⠭", "⠹⠭");
        text = text.replace("⠹⠭⠭", "⠹⠹");
        text = text.replace("⠈⠹⠑", "⠹⠑");
        text = text.replace("⠹⠑⠑", "⠹⠢");
        text = text.replace("⠹⠢⠪", "⠹⠑⠪");
        text = text.replace("⠈⠹⠈⠹", "⠹⠥");
        text = text.replace("⠹⠥⠥", "⠹⠳");
        text = text.replace("⠹⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠹⠥", "⠹⠳");

        text = text.replace("ද්හ්", "ධ්");

        text = text.replace("⠈⠏⠈⠓", "⠈⠱");
        text = text.replace("⠈⠱⠁", "⠱");
        text = text.replace("⠱⠁", "⠱⠜");
        text = text.replace("⠈⠱⠪", "⠱⠪");
        text = text.replace("⠱⠪⠪", "⠱⠔");
        text = text.replace("⠈⠱⠭", "⠱⠭");
        text = text.replace("⠱⠭⠭", "⠱⠱");
        text = text.replace("⠈⠱⠑", "⠱⠑");
        text = text.replace("⠱⠑⠑", "⠱⠢");
        text = text.replace("⠱⠢⠪", "⠱⠑⠪");
        text = text.replace("⠈⠱⠈⠱", "⠱⠥");
        text = text.replace("⠱⠥⠥", "⠱⠳");
        text = text.replace("⠱⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠱⠥", "⠱⠳");

        text = text.replace("⠈⠃⠈⠓", "⠈⠘");
        text = text.replace("⠈⠘⠁", "⠘");
        text = text.replace("⠘⠁", "⠘⠜");
        text = text.replace("⠈⠘⠪", "⠘⠪");
        text = text.replace("⠘⠪⠪", "⠘⠔");
        text = text.replace("⠈⠘⠭", "⠘⠭");
        text = text.replace("⠘⠭⠭", "⠘⠘");
        text = text.replace("⠈⠘⠑", "⠘⠑");
        text = text.replace("⠘⠑⠑", "⠘⠢");
        text = text.replace("⠘⠢⠪", "⠘⠑⠪");
        text = text.replace("⠈⠘⠈⠘", "⠘⠥");
        text = text.replace("⠘⠥⠥", "⠘⠳");
        text = text.replace("⠘⠜A", "⠜⠷");
        text = text.replace("⠜⠷⠁", "⠜⠻");
        text = text.replace("⠘⠥", "⠘⠳");
        //********************************************************
        if (a==1) 
        {
             SinhalaBrail.jTextArea1.setText(text);
        }
        else if(a==2)
        {
            SinhalaBrailTBYEnglish.jTextArea1.setText(text);
        }
        else if(a==3)
        {
            SinhalaBrailTBYTamil.jTextArea1.setText(text);
        }
        
       //adooo
        
    }

    public static void convertEnglishToBraille(String p,int a) {
        String text = p;
        text = text.replace("a", "⠁");
        text = text.replace("b", "⠃");
        text = text.replace("c", "⠉");
        text = text.replace("d", "⠙");
        text = text.replace("e", "⠑");
        text = text.replace("f", "⠋");
        text = text.replace("g", "⠛");
        text = text.replace("h", "⠓");
        text = text.replace("i", "⠊");
        text = text.replace("j", "⠚");
        text = text.replace("k", "⠅");
        text = text.replace("l", "⠇");
        text = text.replace("m", "⠍");
        text = text.replace("n", "⠝");
        text = text.replace("o", "⠕");
        text = text.replace("p", "⠏");
        text = text.replace("q", "⠟");
        text = text.replace("r", "⠗");
        text = text.replace("s", "⠎");
        text = text.replace("t", "⠞");
        text = text.replace("u", "⠥");
        text = text.replace("v", "⠧");
        text = text.replace("w", "⠺");
        text = text.replace("x", "⠭");
        text = text.replace("y", "⠽");
        text = text.replace("z", "⠵");

        text = text.replace("A", "⠁");
        text = text.replace("B", "⠃");
        text = text.replace("C", "⠉");
        text = text.replace("D", "⠙");
        text = text.replace("E", "⠑");
        text = text.replace("F", "⠋");
        text = text.replace("G", "⠛");
        text = text.replace("H", "⠓");
        text = text.replace("I", "⠊");
        text = text.replace("J", "⠚");
        text = text.replace("K", "⠅");
        text = text.replace("L", "⠇");
        text = text.replace("M", "⠍");
        text = text.replace("N", "⠝");
        text = text.replace("O", "⠕");
        text = text.replace("P", "⠏");
        text = text.replace("Q", "⠟");
        text = text.replace("R", "⠗");
        text = text.replace("S", "⠎");
        text = text.replace("T", "⠞");
        text = text.replace("U", "⠥");
        text = text.replace("V", "⠧");
        text = text.replace("W", "⠺");
        text = text.replace("X", "⠭");
        text = text.replace("Y", "⠽");
        text = text.replace("Z", "⠵");
        
        if(a==1)
        {
            EnglishBrail.jTextArea1.setText(text);
        }
        else if(a==2)
        {
            EnglishBrailbyTamil.jTextArea1.setText(text);
        }
        else if(a==3)
        {
            EnglishBrailbySinhala.jTextArea1.setText(text);
        }
        
    }

    public static void convertTamilToBraille(String p,int a)
    {
        String text = p;
        text = text.replace("அ", "⠁");
        text = text.replace("ஆ", "⠜");
        text = text.replace("இ", "⠊");
        text = text.replace("ஈ", "⠔");
        text = text.replace("உ", "⠥");
        text = text.replace("ஊ", "⠳");
        text = text.replace("எ", "⠑");
        text = text.replace("ஏ", "⠢");
        text = text.replace("ஒ", "⠕");
        text = text.replace("ஓ", "⠢");
        text = text.replace("ஔ", "⠪");
        text = text.replace("ஐ", "⠌");
        text = text.replace("ஃ", "⠿");

        text = text.replace("க்", "⠈⠅");
        text = text.replace("கா", "⠅⠜");
        text = text.replace("கி", "⠅⠊");
        text = text.replace("கீ", "⠅⠔");
        text = text.replace("கு", "⠅⠥");
        text = text.replace("கூ", "⠅⠳");
        text = text.replace("கெ", "⠅⠑");
        text = text.replace("கே", "⠅⠢");
        text = text.replace("கொ", "⠅⠭");
        text = text.replace("கோ", "⠗⠕");
        text = text.replace("கௌ", "⠅⠪");
        text = text.replace("கை", "⠅⠌");
        text = text.replace("க", "⠅");

        text = text.replace("க்", "⠈⠅");
        text = text.replace("கா", "⠅⠜");
        text = text.replace("கி", "⠅⠊");
        text = text.replace("கீ", "⠅⠔");
        text = text.replace("கு", "⠅⠥");
        text = text.replace("கூ", "⠅⠳");
        text = text.replace("கெ", "⠅⠑");
        text = text.replace("கே", "⠅⠢");
        text = text.replace("கொ", "⠅⠭");
        text = text.replace("கோ", "⠗⠕");
        text = text.replace("கௌ", "⠅⠪");
        text = text.replace("கை", "⠅⠌");
        text = text.replace("க", "⠅");

        text = text.replace("ங்", "⠈⠬");
        text = text.replace("ஙா", "⠬⠜");
        text = text.replace("ஙி", "⠬⠊");
        text = text.replace("ஙீ", "⠬⠔");
        text = text.replace("ஙு", "⠬⠥");
        text = text.replace("ஙூ", "⠬⠳");
        text = text.replace("ஙெ", "⠬⠑");
        text = text.replace("ஙே", "⠬⠢");
        text = text.replace("ஙொ", "⠬⠭");
        text = text.replace("ஙோ", "⠬⠪");
        text = text.replace("ஙௌ", "⠬⠪");
        text = text.replace("ஙை", "⠬⠌");
        text = text.replace("ங", "⠬");

        text = text.replace("ச்", "⠈⠉");
        text = text.replace("சா", "⠉⠜");
        //text = text.replace("sA", "சா");
        text = text.replace("சி", "⠉⠊");
        text = text.replace("சீ", "⠉⠔");
        //text = text.replace("sI", "சீ");
        text = text.replace("சு", "⠉⠥");
        text = text.replace("சூ", "⠉⠳");
        //text = text.replace("sU", "சூ");
        text = text.replace("செ", "⠉⠑");
        text = text.replace("சே", "⠉⠢");
        //text = text.replace("sE", "சே");
        text = text.replace("சை", "⠉⠌");
        text = text.replace("சொ", "⠉⠭");
        text = text.replace("சோ", "⠉⠕");
        //text = text.replace("sO", "சோ");
        text = text.replace("சௌ", "⠉⠪");
        text = text.replace("ச", "⠉");

        text = text.replace("ச்", "⠈⠉");
        text = text.replace("சா", "⠉⠜");
        //text = text.replace("sA", "சா");
        text = text.replace("சி", "⠉⠊");
        text = text.replace("சீ", "⠉⠔");
        //text = text.replace("sI", "சீ");
        text = text.replace("சு", "⠉⠥");
        text = text.replace("சூ", "⠉⠳");
        //text = text.replace("sU", "சூ");
        text = text.replace("செ", "⠉⠑");
        text = text.replace("சே", "⠉⠢");
        //text = text.replace("sE", "சே");
        text = text.replace("சை", "⠉⠌");
        text = text.replace("சொ", "⠉⠭");
        text = text.replace("சோ", "⠉⠕");
        //text = text.replace("sO", "சோ");
        text = text.replace("சௌ", "⠉⠪");
        text = text.replace("ச", "⠉");

        text = text.replace("ஞ்", "⠈⠒");
        text = text.replace("ஞா", "⠒⠜");
        //text = text.replace("knA", "ஞா");
        text = text.replace("ஞி", "⠒⠊");
        text = text.replace("ஞீ", "⠒⠔");
        //text = text.replace("knI", "ஞீ");
        text = text.replace("ஞு", "⠒⠥");
        text = text.replace("ஞூ", "⠒⠳");
        //text = text.replace("knU", "ஞூ");
        text = text.replace("ஞெ", "⠒⠑");
        text = text.replace("ஞே", "⠒⠢");
        //text = text.replace("knE", "ஞே");
        text = text.replace("ஞை", "⠒⠌");
        text = text.replace("ஞொ", "⠒⠭");
        text = text.replace("ஞோ", "⠒⠕");
        //text = text.replace("knO", "ஞோ");
        text = text.replace("ஞௌ", "⠒⠪");
        text = text.replace("ஞ", "⠒");

        text = text.replace("ட்", "⠈⠾");
        text = text.replace("டா", "⠾⠜");
        //text = text.replace("tA", "டா");
        text = text.replace("டி", "⠾⠊");
        text = text.replace("டீ", "⠾⠔");
        //text = text.replace("tI", "டீ");
        text = text.replace("டு", "⠾⠥");
        text = text.replace("டூ", "⠾⠳");
        //text = text.replace("tU", "டூ");
        text = text.replace("டெ", "⠾⠑");
        text = text.replace("டே", "⠾⠢");
        //text = text.replace("tE", "டே");
        text = text.replace("டை", "⠾⠌");
        text = text.replace("டொ", "⠾⠭");
        text = text.replace("டோ", "⠾⠕");
        //text = text.replace("tO", "டோ");
        text = text.replace("டௌ", "⠾⠪");
        text = text.replace("ட", "⠾");

        text = text.replace("ட்", "⠈⠾");
        text = text.replace("டா", "⠾⠜");
        //text = text.replace("tA", "டா");
        text = text.replace("டி", "⠾⠊");
        text = text.replace("டீ", "⠾⠔");
        //text = text.replace("tI", "டீ");
        text = text.replace("டு", "⠾⠥");
        text = text.replace("டூ", "⠾⠳");
        //text = text.replace("tU", "டூ");
        text = text.replace("டெ", "⠾⠑");
        text = text.replace("டே", "⠾⠢");
        //text = text.replace("tE", "டே");
        text = text.replace("டை", "⠾⠌");
        text = text.replace("டொ", "⠾⠭");
        text = text.replace("டோ", "⠾⠕");
        //text = text.replace("tO", "டோ");
        text = text.replace("டௌ", "⠾⠪");
        text = text.replace("ட", "⠾");

        text = text.replace("ண்", "⠈⠼");
        text = text.replace("ணா", "⠼⠜");
        //text = text.replace("NA", "சா");
        text = text.replace("ணி", "⠼⠊");
        text = text.replace("ணீ", "⠼⠔");
        //text = text.replace("NI", "சீ");
        text = text.replace("ணு", "⠼⠥");
        text = text.replace("ணூ", "⠼⠳");
        //text = text.replace("NU", "சூ");
        text = text.replace("ணெ", "⠼⠑");
        text = text.replace("ணே", "⠼⠢");
        //text = text.replace("NE", "சே");
        text = text.replace("ணை", "⠼⠌");
        text = text.replace("ணொ", "⠼⠭");
        text = text.replace("ணோ", "⠼⠕");
        //text = text.replace("NO", "சோ");
        text = text.replace("ணௌ", "⠼⠪");
        text = text.replace("ண", "⠼");

        text = text.replace("த்", "⠈⠞");
        text = text.replace("தா", "⠞⠜");
        //text = text.replace("tA", "சா");
        text = text.replace("தி", "⠞⠊");
        text = text.replace("தீ", "⠞⠔");
        //text = text.replace("tI", "சீ");
        text = text.replace("து", "⠞⠥");
        text = text.replace("தூ", "⠞⠳");
        //text = text.replace("tU", "சூ");
        text = text.replace("தெ", "⠞⠑");
        text = text.replace("தே", "⠞⠢");
        //text = text.replace("tE", "சே");
        text = text.replace("தை", "⠞⠌");
        text = text.replace("தொ", "⠞⠭");
        text = text.replace("தோ", "⠞⠕");
        //text = text.replace("tO", "சோ");
        text = text.replace("தௌ", "⠞⠪");
        text = text.replace("த", "⠞");


        text = text.replace("த்", "⠈⠞");
        text = text.replace("தா", "⠞⠜");
        //text = text.replace("tA", "சா");
        text = text.replace("தி", "⠞⠊");
        text = text.replace("தீ", "⠞⠔");
        //text = text.replace("tI", "சீ");
        text = text.replace("து", "⠞⠥");
        text = text.replace("தூ", "⠞⠳");
        //text = text.replace("tU", "சூ");
        text = text.replace("தெ", "⠞⠑");
        text = text.replace("தே", "⠞⠢");
        //text = text.replace("tE", "சே");
        text = text.replace("தை", "⠞⠌");
        text = text.replace("தொ", "⠞⠭");
        text = text.replace("தோ", "⠞⠕");
        //text = text.replace("tO", "சோ");
        text = text.replace("தௌ", "⠞⠪");
        text = text.replace("த", "⠞");

        text = text.replace("ந்", "⠈⠝");
        text = text.replace("நா", "⠝⠜");
        //text = text.replace("tA", "சா");
        text = text.replace("நி", "⠝⠊");
        text = text.replace("நீ", "⠝⠔");
        //text = text.replace("tI", "சீ");
        text = text.replace("நு", "⠝⠥");
        text = text.replace("நூ", "⠝⠳");
        //text = text.replace("tU", "சூ");
        text = text.replace("நெ", "⠝⠑");
        text = text.replace("நே", "⠝⠢");
        //text = text.replace("tE", "சே");
        text = text.replace("நை", "⠝⠌");
        text = text.replace("நொ", "⠝⠭");
        text = text.replace("நோ", "⠝⠕");
        //text = text.replace("tO", "சோ");
        text = text.replace("நௌ", "⠝⠪");
        text = text.replace("ந", "⠝");

        text = text.replace("ப்", "⠈⠏");
        text = text.replace("பா", "⠏⠜");
        //text = text.replace("tA", "சா");
        text = text.replace("பி", "⠏⠊");
        text = text.replace("பீ", "⠏⠔");
        //text = text.replace("tI", "சீ");
        text = text.replace("பு", "⠏⠥");
        text = text.replace("பூ", "⠏⠳");
        //text = text.replace("tU", "சூ");
        text = text.replace("பெ", "⠏⠑");
        text = text.replace("பே", "⠏⠢");
        //text = text.replace("tE", "சே");
        text = text.replace("பை", "⠏⠌");
        text = text.replace("பொ", "⠏⠭");
        text = text.replace("போ", "⠏⠕");
        //text = text.replace("tO", "சோ");
        text = text.replace("பௌ", "⠏⠪");
        text = text.replace("ப", "⠏");

        text = text.replace("ப்", "⠈⠏");
        text = text.replace("பா", "⠏⠜");
        //text = text.replace("tA", "சா");
        text = text.replace("பி", "⠏⠊");
        text = text.replace("பீ", "⠏⠔");
        //text = text.replace("tI", "சீ");
        text = text.replace("பு", "⠏⠥");
        text = text.replace("பூ", "⠏⠳");
        //text = text.replace("tU", "சூ");
        text = text.replace("பெ", "⠏⠑");
        text = text.replace("பே", "⠏⠢");
        //text = text.replace("tE", "சே");
        text = text.replace("பை", "⠏⠌");
        text = text.replace("பொ", "⠏⠭");
        text = text.replace("போ", "⠏⠕");
        //text = text.replace("tO", "சோ");
        text = text.replace("பௌ", "⠏⠪");
        text = text.replace("ப", "⠏");

        text = text.replace("ம்", "⠈⠍");
        text = text.replace("மா", "⠍⠜");
        //text = text.replace("tA", "சா");
        text = text.replace("மி", "⠍⠊");
        text = text.replace("மீ", "⠍⠔");
        //text = text.replace("tI", "சீ");
        text = text.replace("மு", "⠍⠥");
        text = text.replace("மூ", "⠍⠳");
        //text = text.replace("tU", "சூ");
        text = text.replace("மெ", "⠍⠑");
        text = text.replace("மே", "⠍⠢");
        //text = text.replace("tE", "சே");
        text = text.replace("மை", "⠍⠌");
        text = text.replace("மொ", "⠍⠭");
        text = text.replace("மோ", "⠍⠕");
        //text = text.replace("tO", "சோ");
        text = text.replace("மௌ", "⠍⠪");
        text = text.replace("ம", "⠍");

        text = text.replace("ய்", "⠈⠽");
        text = text.replace("யா", "⠽⠜");
        //text = text.replace("tA", "சா");
        text = text.replace("யி", "⠽⠊");
        text = text.replace("யீ", "⠽⠔");
        //text = text.replace("tI", "சீ");
        text = text.replace("யு", "⠽⠥");
        text = text.replace("யூ", "⠽⠳");
        //text = text.replace("tU", "சூ");
        text = text.replace("யெ", "⠽⠑");
        text = text.replace("யே", "⠽⠢");
        //text = text.replace("tE", "சே");
        text = text.replace("யை", "⠽⠌");
        text = text.replace("யொ", "⠽⠭");
        text = text.replace("யோ", "⠽⠕");
        //text = text.replace("tO", "சோ");
        text = text.replace("யௌ", "⠽⠪");
        text = text.replace("ய", "⠽");

        text = text.replace("ர்", "⠈⠗");
        text = text.replace("ரா", "⠗⠜");
        //text = text.replace("tA", "சா");
        text = text.replace("ரி", "⠗⠊");
        text = text.replace("ரீ", "⠗⠔");
        //text = text.replace("tI", "சீ");
        text = text.replace("ரு", "⠗⠥");
        text = text.replace("ரூ", "⠗⠳");
        //text = text.replace("tU", "சூ");
        text = text.replace("ரெ", "⠗⠑");
        text = text.replace("ரே", "⠗⠢");
        //text = text.replace("tE", "சே");
        text = text.replace("ரை", "⠗⠌");
        text = text.replace("ரொ", "⠗⠭");
        text = text.replace("ரோ", "⠗⠕");
        //text = text.replace("tO", "சோ");
        text = text.replace("ரௌ", "⠗⠪");
        text = text.replace("ர", "⠗");
        
        text = text.replace("ல்", "⠈⠇");
        text = text.replace("லா", "⠇⠜");
        //text = text.replace("tA", "சா");
        text = text.replace("லி", "⠇⠊");
        text = text.replace("லீ", "⠇⠔");
        //text = text.replace("tI", "சீ");
        text = text.replace("லு", "⠇⠥");
        text = text.replace("லூ", "⠇⠳");
        //text = text.replace("tU", "சூ");
        text = text.replace("லெ", "⠇⠑");
        text = text.replace("லே", "⠇⠢");
        //text = text.replace("tE", "சே");
        text = text.replace("லை", "⠇⠌");
        text = text.replace("லொ", "⠇⠭");
        text = text.replace("லோ", "⠇⠕");
        //text = text.replace("tO", "சோ");
        text = text.replace("லௌ", "⠇⠪");
        text = text.replace("ல", "⠇");

        text = text.replace("வ்", "⠈⠗");
        text = text.replace("வா", "⠗⠜");
        //text = text.replace("tA", "சா");
        text = text.replace("வி", "⠗⠊");
        text = text.replace("வீ", "⠗⠔");
        //text = text.replace("tI", "சீ");
        text = text.replace("வு", "⠗⠥");
        text = text.replace("வூ", "⠗⠳");
        //text = text.replace("tU", "சூ");
        text = text.replace("வெ", "⠗⠑");
        text = text.replace("வே", "⠗⠢");
        //text = text.replace("tE", "சே");
        text = text.replace("வை", "⠗⠌");
        text = text.replace("வொ", "⠗⠭");
        text = text.replace("வோ", "⠗⠕");
        //text = text.replace("tO", "சோ");
        text = text.replace("வௌ", "⠗⠪");
        text = text.replace("வ", "⠗");

        text = text.replace("வ்", "⠈⠗");
        text = text.replace("வா", "⠗⠜");
        //text = text.replace("tA", "சா");
        text = text.replace("வி", "⠗⠊");
        text = text.replace("வீ", "⠗⠔");
        //text = text.replace("tI", "சீ");
        text = text.replace("வு", "⠗⠥");
        text = text.replace("வூ", "⠗⠳");
        //text = text.replace("tU", "சூ");
        text = text.replace("வெ", "⠗⠑");
        text = text.replace("வே", "⠗⠢");
        //text = text.replace("tE", "சே");
        text = text.replace("வை", "⠗⠌");
        text = text.replace("வொ", "⠗⠭");
        text = text.replace("வோ", "⠗⠕");
        //text = text.replace("tO", "சோ");
        text = text.replace("வௌ", "⠗⠪");
        text = text.replace("வ", "⠗");

        text = text.replace("ள்", "⠈⠸");
        text = text.replace("ளா", "⠸⠜");
        //text = text.replace("tA", "சா");
        text = text.replace("ளி", "⠸⠊");
        text = text.replace("ளீ", "⠸⠔");
        //text = text.replace("tI", "சீ");
        text = text.replace("ளு", "⠸⠥");
        text = text.replace("ளூ", "⠸⠳");
        //text = text.replace("tU", "சூ");
        text = text.replace("ளெ", "⠸⠑");
        text = text.replace("ளே", "⠸⠢");
        //text = text.replace("tE", "சே");
        text = text.replace("ளை", "⠸⠌");
        text = text.replace("ளொ", "⠸⠭");
        text = text.replace("ளோ", "⠸⠕");
        //text = text.replace("tO", "சோ");
        text = text.replace("ளௌ", "⠸⠪");
        text = text.replace("ள", "⠸");

        text = text.replace("ழ்", "⠈⠷");
        text = text.replace("ழா", "⠷⠜");
        //text = text.replace("tA", "சா");
        text = text.replace("ழி", "⠷⠊");
        text = text.replace("ழீ", "⠷⠔");
        //text = text.replace("tI", "சீ");
        text = text.replace("ழு", "⠷⠥");
        text = text.replace("ழூ", "⠷⠳");
        //text = text.replace("tU", "சூ");
        text = text.replace("ழெ", "⠷⠑");
        text = text.replace("ழே", "⠷⠢");
        //text = text.replace("tE", "சே");
        text = text.replace("ழை", "⠷⠌");
        text = text.replace("ழொ", "⠷⠭");
        text = text.replace("ழோ", "⠷⠕");
        //text = text.replace("tO", "சோ");
        text = text.replace("ழௌ", "⠷⠪");
        text = text.replace("ழ", "⠷");

        text = text.replace("ற்", "⠈⠻");
        text = text.replace("றா", "⠻⠜");
        //text = text.replace("tA", "சா");
        text = text.replace("றி", "⠻⠊");
        text = text.replace("றீ", "⠻⠔");
        //text = text.replace("tI", "சீ");
        text = text.replace("று", "⠻⠥");
        text = text.replace("றூ", "⠻⠳");
        //text = text.replace("tU", "சூ");
        text = text.replace("றெ", "⠻⠑");
        text = text.replace("றே", "⠻⠢");
        //text = text.replace("tE", "சே");
        text = text.replace("றை", "⠻⠌");
        text = text.replace("றொ", "⠻⠭");
        text = text.replace("றோ", "⠻⠕");
        //text = text.replace("tO", "சோ");
        text = text.replace("றௌ", "⠻⠪");
        text = text.replace("ற", "⠻");

        text = text.replace("ன்", "⠈⠰");
        text = text.replace("னா", "⠰⠜");
        //text = text.replace("tA", "சா");
        text = text.replace("னி", "⠰⠊");
        text = text.replace("னீ", "⠰⠔");
        //text = text.replace("tI", "சீ");
        text = text.replace("னு", "⠰⠥");
        text = text.replace("னூ", "⠰⠳");
        //text = text.replace("tU", "சூ");
        text = text.replace("னெ", "⠰⠑");
        text = text.replace("னே", "⠰⠢");
        //text = text.replace("tE", "சே");
        text = text.replace("னை", "⠰⠌");
        text = text.replace("னொ", "⠰⠭");
        text = text.replace("னோ", "⠰⠕");
        //text = text.replace("tO", "சோ");
        text = text.replace("னௌ", "⠰⠪");
        text = text.replace("ன", "⠰");

        text = text.replace("ஸ்", "⠈⠎");
        text = text.replace("ஸா", "⠎⠜");
        //text = text.replace("tA", "சா");
        text = text.replace("ஸி", "⠎⠊");
        text = text.replace("ஸீ", "⠎⠔");
        //text = text.replace("tI", "சீ");
        text = text.replace("ஸு", "⠎⠥");
        text = text.replace("ஸூ", "⠎⠳");
        //text = text.replace("tU", "சூ");
        text = text.replace("ஸெ", "⠎⠑");
        text = text.replace("ஸே", "⠎⠢");
        //text = text.replace("tE", "சே");
        text = text.replace("ஸை", "⠎⠌");
        text = text.replace("ஸொ", "⠎⠭");
        text = text.replace("ஸோ", "⠎⠕");
        //text = text.replace("tO", "சோ");
        text = text.replace("ஸௌ", "⠎⠪");
        text = text.replace("ஸ", "⠎");

        text = text.replace("ஹ்", "⠈⠓");
        text = text.replace("ஹா", "⠓⠜");
        //text = text.replace("tA", "சா");
        text = text.replace("ஹி", "⠓⠊");
        text = text.replace("ஹீ", "⠓⠔");
        //text = text.replace("tI", "சீ");
        text = text.replace("ஹு", "⠓⠥");
        text = text.replace("ஹூ", "⠓⠳");
        //text = text.replace("tU", "சூ");
        text = text.replace("ஹெ", "⠓⠑");
        text = text.replace("ஹே", "⠓⠢");
        //text = text.replace("tE", "சே");
        text = text.replace("ஹை", "⠓⠌");
        text = text.replace("ஹொ", "⠓⠭");
        text = text.replace("ஹோ", "⠓⠕");
        //text = text.replace("tO", "சோ");
        text = text.replace("ஹௌ", "⠓⠪");
        text = text.replace("ஹ", "⠓");

        text = text.replace("ஷ்", "⠈⠩");
        text = text.replace("ஷா", "⠩⠜");
        //text = text.replace("tA", "சா");
        text = text.replace("ஷி", "⠩⠊");
        text = text.replace("ஷீ", "⠩⠔");
        //text = text.replace("tI", "சீ");
        text = text.replace("ஷு", "⠩⠥");
        text = text.replace("ஷூ", "⠩⠳");
        //text = text.replace("tU", "சூ");
        text = text.replace("ஷெ", "⠩⠑");
        text = text.replace("ஷே", "⠩⠢");
        //text = text.replace("tE", "சே");
        text = text.replace("ஷை", "⠩⠌");
        text = text.replace("ஷொ", "⠩⠭");
        text = text.replace("ஷோ", "⠩⠕");
        //text = text.replace("tO", "சோ");
        text = text.replace("ஷௌ", "⠩⠪");
        text = text.replace("ஷ", "⠩");

        text = text.replace("ஜ்", "⠈⠚");
        text = text.replace("ஜா", "⠚⠜");
        //text = text.replace("tA", "சா");
        text = text.replace("ஜி", "⠚⠊");
        text = text.replace("ஜீ", "⠚⠔");
        //text = text.replace("tI", "சீ");
        text = text.replace("ஜு", "⠚⠥");
        text = text.replace("ஜூ", "⠚⠳");
        //text = text.replace("tU", "சூ");
        text = text.replace("ஜெ", "⠚⠑");
        text = text.replace("ஜே", "⠚⠢");
        //text = text.replace("tE", "சே");
        text = text.replace("ஜை", "⠚⠌");
        text = text.replace("ஜொ", "⠚⠭");
        text = text.replace("ஜோ", "⠚⠕");
        //text = text.replace("tO", "சோ");
        text = text.replace("ஜௌ", "⠚⠪");
        text = text.replace("ஜ", "⠚");
        
        //********************************************
         text = text.replace("a", "⠁");
            text = text.replace("⠁⠁", "⠜");
            //text = text.replace("A", "ஆ");

            text = text.replace("i", "⠊");
            text = text.replace("⠊⠊", "⠔");
            //text = text.replace("I", "ஈ");

            text = text.replace("u", "⠥");
            text = text.replace("⠥⠥", "⠳");
            // text = text.replace("U", "ஊ");

            text = text.replace("e", "⠢");
            text = text.replace("⠢⠢", "⠑");
            // text = text.replace("E", "ஏ");

            text = text.replace("o", "⠭");
            text = text.replace("⠭⠭", "⠕");
            //text = text.replace("O", "ஓ");

            text = text.replace("⠁⠥", "⠪");
            text = text.replace("⠁⠊", "⠌");

            text = text.replace("x", "⠠");

            //text = text.replace("x", "௯");


            text = text.replace("k", "⠈⠅");
            text = text.replace("⠈⠅⠁", "⠅");
            text = text.replace("⠅⠁", "⠅⠜");
            text = text.replace("⠈⠅⠊", "⠅⠊");
            text = text.replace("⠅⠊⠊", "⠅⠔");
            text = text.replace("⠈⠅⠥", "⠅⠥");
            text = text.replace("⠅⠥⠥", "⠅⠳");
            text = text.replace("⠈⠅⠢", "⠅⠢");
            text = text.replace("⠅⠢⠢", "⠅⠑");
            text = text.replace("⠈⠅⠭", "⠅⠭");
            text = text.replace("⠅⠭⠭", "⠅⠕");
            text = text.replace("⠅⠥", "⠅⠪");
            text = text.replace("⠅⠊", "⠅⠌");


            text = text.replace("g", "⠈⠅");
            text = text.replace("⠈⠅⠁", "⠅");
            text = text.replace("⠅⠁", "⠅⠜");
            text = text.replace("⠈⠅⠊", "⠅⠊");
            text = text.replace("⠅⠊⠊", "⠅⠔");
            text = text.replace("⠈⠅⠥", "⠅⠥");
            text = text.replace("⠅⠥⠥", "⠅⠳");
            text = text.replace("⠈⠅⠢", "⠅⠢");
            text = text.replace("⠅⠢⠢", "⠅⠑");
            text = text.replace("⠈⠅⠭", "⠅⠭");
            text = text.replace("⠅⠭⠭", "⠅⠕");
            text = text.replace("⠅⠥", "⠅⠪");
            text = text.replace("⠅⠊", "⠅⠌");


            text = text.replace("⠈⠅n", "⠈⠬");
            text = text.replace("⠈⠬⠁", "⠬");
            text = text.replace("⠬⠁", "⠬⠜");
            text = text.replace("⠈⠬⠊", "⠬⠊");
            text = text.replace("⠬⠊⠊", "⠬⠔");
            text = text.replace("⠈⠬⠥", "⠬⠥");
            text = text.replace("⠬⠥⠥", "⠬⠳");
            text = text.replace("⠈⠬⠢", "⠬⠢");
            text = text.replace("⠬⠢⠢", "⠬⠑");
            text = text.replace("⠈⠬⠭", "⠬⠭");
            text = text.replace("⠬⠭⠭", "⠬⠕");
            text = text.replace("⠬⠥", "⠬⠪");
            text = text.replace("⠬⠊", "⠬⠌");


            text = text.replace("s", "⠈⠉");
            text = text.replace("⠈⠉⠁", "⠉");
            text = text.replace("⠉⠁", "⠉⠜");
            text = text.replace("⠈⠉⠊", "⠉⠊");
            text = text.replace("⠉⠊⠊", "⠉⠔");
            text = text.replace("⠈⠉⠥", "⠉⠥");
            text = text.replace("⠉⠥⠥", "⠉⠳");
            text = text.replace("⠈⠉⠢", "⠉⠢");
            text = text.replace("⠉⠢⠢", "⠉⠑");
            text = text.replace("⠈⠉⠭", "⠉⠭");
            text = text.replace("⠉⠭⠭", "⠉⠕");
            text = text.replace("⠉⠥", "⠉⠪");
            text = text.replace("⠉⠊", "⠉⠌");

            text = text.replace("ch", "⠈⠉");
            text = text.replace("⠈⠉⠁", "⠉");
            text = text.replace("⠉⠁", "⠉⠜");
            text = text.replace("⠈⠉⠊", "⠉⠊");
            text = text.replace("⠉⠊⠊", "⠉⠔");
            text = text.replace("⠈⠉⠥", "⠉⠥");
            text = text.replace("⠉⠥⠥", "⠉⠳");
            text = text.replace("⠈⠉⠢", "⠉⠢");
            text = text.replace("⠉⠢⠢", "⠉⠑");
            text = text.replace("⠈⠉⠭", "⠉⠭");
            text = text.replace("⠉⠭⠭", "⠉⠕");
            text = text.replace("⠉⠥", "⠉⠪");
            text = text.replace("⠉⠊", "⠉⠌");

            text = text.replace("⠈⠅n", "⠈⠒");
            text = text.replace("⠈⠒⠁", "⠒");
            text = text.replace("⠒⠁", "⠒⠜");
            text = text.replace("⠈⠒⠊", "⠒⠊");
            text = text.replace("⠒⠊⠊", "⠒⠔");
            text = text.replace("⠈⠒⠥", "⠒⠥");
            text = text.replace("⠒⠥⠥", "⠒⠳");
            text = text.replace("⠈⠒⠢", "⠒⠢");
            text = text.replace("⠒⠢⠢", "⠒⠑");
            text = text.replace("⠈⠒⠭", "⠒⠭");
            text = text.replace("⠒⠭⠭", "⠒⠕");
            text = text.replace("⠒⠥", "⠒⠪");
            text = text.replace("⠒⠊", "⠒⠌");

            text = text.replace("t", "⠈⠾");
            text = text.replace("⠈⠾⠁", "⠾");
            text = text.replace("⠾⠁", "⠾⠜");
            text = text.replace("⠈⠾⠊", "⠾⠊");
            text = text.replace("⠾⠊⠊", "⠾⠔");
            text = text.replace("⠈⠾⠥", "⠾⠥");
            text = text.replace("⠾⠥⠥", "⠾⠳");
            text = text.replace("⠈⠾⠢", "⠾⠢");
            text = text.replace("⠾⠢⠢", "⠾⠑");
            text = text.replace("⠈⠾⠭", "⠾⠭");
            text = text.replace("⠾⠭⠭", "⠾⠕");
            text = text.replace("⠾⠥", "⠾⠪");
            text = text.replace("⠾⠊", "⠾⠌");

            text = text.replace("d", "⠈⠾");
            text = text.replace("⠈⠾⠁", "⠾");
            text = text.replace("⠾⠁", "⠾⠜");
            text = text.replace("⠈⠾⠊", "⠾⠊");
            text = text.replace("⠾⠊⠊", "⠾⠔");
            text = text.replace("⠈⠾⠥", "⠾⠥");
            text = text.replace("⠾⠥⠥", "⠾⠳");
            text = text.replace("⠈⠾⠢", "⠾⠢");
            text = text.replace("⠾⠢⠢", "⠾⠑");
            text = text.replace("⠈⠾⠭", "⠾⠭");
            text = text.replace("⠾⠭⠭", "⠾⠕");
            text = text.replace("⠾⠥", "⠾⠪");
            text = text.replace("⠾⠊", "⠾⠌");

            text = text.replace("N", "⠈⠼");
            text = text.replace("⠈⠼⠁", "⠼");
            text = text.replace("⠼⠁", "⠼⠜");
            text = text.replace("⠈⠼⠊", "⠼⠊");
            text = text.replace("⠼⠊⠊", "⠼⠔");
            text = text.replace("⠈⠼⠥", "⠼⠥");
            text = text.replace("⠼⠥⠥", "⠼⠳");
            text = text.replace("⠈⠼⠢", "⠼⠢");
            text = text.replace("⠼⠢⠢", "⠼⠑");
            text = text.replace("⠈⠼⠭", "⠼⠭");
            text = text.replace("⠼⠭⠭", "⠼⠕");
            text = text.replace("⠼⠥", "⠼⠪");
            text = text.replace("⠼⠊", "⠼⠌");

            text = text.replace("⠈⠾h", "⠈⠞");
            text = text.replace("⠈⠞⠁", "⠞");
            text = text.replace("⠞⠁", "⠞⠜");
            text = text.replace("⠈⠞⠊", "⠞⠊");
            text = text.replace("⠞⠊⠊", "⠞⠔");
            text = text.replace("⠈⠞⠥", "⠞⠥");
            text = text.replace("⠞⠥⠥", "⠞⠳");
            text = text.replace("⠈⠞⠢", "⠞⠢");
            text = text.replace("⠞⠢⠢", "⠞⠑");
            text = text.replace("⠈⠞⠭", "⠞⠭");
            text = text.replace("⠞⠭⠭", "⠞⠕");
            text = text.replace("⠞⠥", "⠞⠪");
            text = text.replace("⠞⠊", "⠞⠌");

            text = text.replace("⠈⠾h", "⠈⠞");
            text = text.replace("⠈⠞⠁", "⠞");
            text = text.replace("⠞⠁", "⠞⠜");
            text = text.replace("⠈⠞⠊", "⠞⠊");
            text = text.replace("⠞⠊⠊", "⠞⠔");
            text = text.replace("⠈⠞⠥", "⠞⠥");
            text = text.replace("⠞⠥⠥", "⠞⠳");
            text = text.replace("⠈⠞⠢", "⠞⠢");
            text = text.replace("⠞⠢⠢", "⠞⠑");
            text = text.replace("⠈⠞⠭", "⠞⠭");
            text = text.replace("⠞⠭⠭", "⠞⠕");
            text = text.replace("⠞⠥", "⠞⠪");
            text = text.replace("⠞⠊", "⠞⠌");

            text = text.replace("n", "⠈⠝");
            text = text.replace("⠈⠝⠁", "⠝");
            text = text.replace("⠝⠁", "⠝⠜");
            text = text.replace("⠈⠝⠊", "⠝⠊");
            text = text.replace("⠝⠊⠊", "⠝⠔");
            text = text.replace("⠈⠝⠥", "⠝⠥");
            text = text.replace("⠝⠥⠥", "⠝⠳");
            text = text.replace("⠈⠝⠢", "⠝⠢");
            text = text.replace("⠝⠢⠢", "⠝⠑");
            text = text.replace("⠈⠝⠭", "⠝⠭");
            text = text.replace("⠝⠭⠭", "⠝⠕");
            text = text.replace("⠝⠥", "⠝⠪");
            text = text.replace("⠝⠊", "⠝⠌");

            text = text.replace("p", "⠈⠏");
            text = text.replace("⠈⠏⠁", "⠏");
            text = text.replace("⠏⠁", "⠏⠜");
            text = text.replace("⠈⠏⠊", "⠏⠊");
            text = text.replace("⠏⠊⠊", "⠏⠔");
            text = text.replace("⠈⠏⠥", "⠏⠥");
            text = text.replace("⠏⠥⠥", "⠏⠳");
            text = text.replace("⠈⠏⠢", "⠏⠢");
            text = text.replace("⠏⠢⠢", "⠏⠑");
            text = text.replace("⠈⠏⠭", "⠏⠭");
            text = text.replace("⠏⠭⠭", "⠏⠕");
            text = text.replace("⠏⠥", "⠏⠪");
            text = text.replace("⠏⠊", "⠏⠌");

            text = text.replace("b", "⠈⠏");
            text = text.replace("⠈⠏⠁", "⠏");
            text = text.replace("⠏⠁", "⠏⠜");
            text = text.replace("⠈⠏⠊", "⠏⠊");
            text = text.replace("⠏⠊⠊", "⠏⠔");
            text = text.replace("⠈⠏⠥", "⠏⠥");
            text = text.replace("⠏⠥⠥", "⠏⠳");
            text = text.replace("⠈⠏⠢", "⠏⠢");
            text = text.replace("⠏⠢⠢", "⠏⠑");
            text = text.replace("⠈⠏⠭", "⠏⠭");
            text = text.replace("⠏⠭⠭", "⠏⠕");
            text = text.replace("⠏⠥", "⠏⠪");
            text = text.replace("⠏⠊", "⠏⠌");

            text = text.replace("m", "⠈⠍");
            text = text.replace("⠈⠍⠁", "⠍");
            text = text.replace("⠍⠁", "⠍⠜");
            text = text.replace("⠈⠍⠊", "⠍⠊");
            text = text.replace("⠍⠊⠊", "⠍⠔");
            text = text.replace("⠈⠍⠥", "⠍⠥");
            text = text.replace("⠍⠥⠥", "⠍⠳");
            text = text.replace("⠈⠍⠢", "⠍⠢");
            text = text.replace("⠍⠢⠢", "⠍⠑");
            text = text.replace("⠈⠍⠭", "⠍⠭");
            text = text.replace("⠍⠭⠭", "⠍⠕");
            text = text.replace("⠍⠥", "⠍⠪");
            text = text.replace("⠍⠊", "⠍⠌");

            text = text.replace("y", "⠈⠽");
            text = text.replace("⠈⠽⠁", "⠽");
            text = text.replace("⠽⠁", "⠽⠜");
            text = text.replace("⠈⠽⠊", "⠽⠊");
            text = text.replace("⠽⠊⠊", "⠽⠔");
            text = text.replace("⠈⠽⠥", "⠽⠥");
            text = text.replace("⠽⠥⠥", "⠽⠳");
            text = text.replace("⠈⠽⠢", "⠽⠢");
            text = text.replace("⠽⠢⠢", "⠽⠑");
            text = text.replace("⠈⠽⠭", "⠽⠭");
            text = text.replace("⠽⠭⠭", "⠽⠕");
            text = text.replace("⠽⠥", "⠽⠪");
            text = text.replace("⠽⠊", "⠽⠌");

            text = text.replace("r", "⠈⠗");
            text = text.replace("⠈⠗⠁", "⠗");
            text = text.replace("⠗⠁", "⠗⠜");
            text = text.replace("⠈⠗⠊", "⠗⠊");
            text = text.replace("⠗⠊⠊", "⠗⠔");
            text = text.replace("⠈⠗⠥", "⠗⠥");
            text = text.replace("⠗⠥⠥", "⠗⠳");
            text = text.replace("⠈⠗⠢", "⠗⠢");
            text = text.replace("⠗⠢⠢", "⠗⠑");
            text = text.replace("⠈⠗⠭", "⠗⠭");
            text = text.replace("⠗⠭⠭", "⠗⠕");
            text = text.replace("⠗⠥", "⠗⠪");
            text = text.replace("⠗⠊", "⠗⠌");

            text = text.replace("l", "⠈⠇");
            text = text.replace("⠈⠇⠁", "⠇");
            text = text.replace("⠇⠁", "⠇⠜");
            text = text.replace("⠈⠇⠊", "⠇⠊");
            text = text.replace("⠇⠊⠊", "⠇⠔");
            text = text.replace("⠈⠇⠥", "⠇⠥");
            text = text.replace("⠇⠥⠥", "⠇⠳");
            text = text.replace("⠈⠇⠢", "⠇⠢");
            text = text.replace("⠇⠢⠢", "⠇⠑");
            text = text.replace("⠈⠇⠭", "⠇⠭");
            text = text.replace("⠇⠭⠭", "⠇⠕");
            text = text.replace("⠇⠥", "⠇⠪");
            text = text.replace("⠇⠊", "⠇⠌");

            text = text.replace("v", "⠈⠧");
            text = text.replace("⠈⠧⠁", "⠧");
            text = text.replace("⠧⠁", "⠧⠜");
            text = text.replace("⠈⠧⠊", "⠧⠊");
            text = text.replace("⠧⠊⠊", "⠧⠔");
            text = text.replace("⠈⠧⠥", "⠧⠥");
            text = text.replace("⠧⠥⠥", "⠧⠳");
            text = text.replace("⠈⠧⠢", "⠧⠢");
            text = text.replace("⠧⠢⠢", "⠧⠑");
            text = text.replace("⠈⠧⠭", "⠧⠭");
            text = text.replace("⠧⠭⠭", "⠧⠕");
            text = text.replace("⠧⠥", "⠧⠪");
            text = text.replace("⠧⠊", "⠧⠌");

            text = text.replace("w", "⠈⠧");
            text = text.replace("⠈⠧⠁", "⠧");
            text = text.replace("⠧⠁", "⠧⠜");
            text = text.replace("⠈⠧⠊", "⠧⠊");
            text = text.replace("⠧⠊⠊", "⠧⠔");
            text = text.replace("⠈⠧⠥", "⠧⠥");
            text = text.replace("⠧⠥⠥", "⠧⠳");
            text = text.replace("⠈⠧⠢", "⠧⠢");
            text = text.replace("⠧⠢⠢", "⠧⠑");
            text = text.replace("⠈⠧⠭", "⠧⠭");
            text = text.replace("⠧⠭⠭", "⠧⠕");
            text = text.replace("⠧⠥", "⠧⠪");
            text = text.replace("⠧⠊", "⠧⠌");

            text = text.replace("L", "⠈⠸");
            text = text.replace("⠈⠸⠁", "⠸");
            text = text.replace("⠸⠁", "⠸⠜");
            text = text.replace("⠈⠸⠊", "⠸⠊");
            text = text.replace("⠸⠊⠊", "⠸⠔");
            text = text.replace("⠈⠸⠥", "⠸⠥");
            text = text.replace("⠸⠥⠥", "⠸⠳");
            text = text.replace("⠈⠸⠢", "⠸⠢");
            text = text.replace("⠸⠢⠢", "⠸⠑");
            text = text.replace("⠈⠸⠭", "⠸⠭");
            text = text.replace("⠸⠭⠭", "⠸⠕");
            text = text.replace("⠸⠥", "⠸⠪");
            text = text.replace("⠸⠊", "⠸⠌");

            text = text.replace("-⠈⠸", "⠈⠷");
            text = text.replace("⠈⠷⠁", "⠷");
            text = text.replace("⠷⠁", "⠷⠜");
            text = text.replace("⠈⠷⠊", "⠷⠊");
            text = text.replace("⠷⠊⠊", "⠷⠔");
            text = text.replace("⠈⠷⠥", "⠷⠥");
            text = text.replace("⠷⠥⠥", "⠷⠳");
            text = text.replace("⠈⠷⠢", "⠷⠢");
            text = text.replace("⠷⠢⠢", "⠷⠑");
            text = text.replace("⠈⠷⠭", "⠷⠭");
            text = text.replace("⠷⠭⠭", "⠷⠕");
            text = text.replace("⠷⠥", "⠷⠪");
            text = text.replace("⠷⠊", "⠷⠌");

            text = text.replace("R", "⠈⠻");
            text = text.replace("⠈⠻⠁", "⠻");
            text = text.replace("⠻⠁", "⠻⠜");
            text = text.replace("⠈⠻⠊", "⠻⠊");
            text = text.replace("⠻⠊⠊", "⠻⠔");
            text = text.replace("⠈⠻⠥", "⠻⠥");
            text = text.replace("⠻⠥⠥", "⠻⠳");
            text = text.replace("⠈⠻⠢", "⠻⠢");
            text = text.replace("⠻⠢⠢", "⠻⠑");
            text = text.replace("⠈⠻⠭", "⠻⠭");
            text = text.replace("⠻⠭⠭", "⠻⠕");
            text = text.replace("⠻⠥", "⠻⠪");
            text = text.replace("⠻⠊", "⠻⠌");

            text = text.replace("-⠈⠼", "⠈⠰");
            text = text.replace("⠈⠰⠁", "⠰");
            text = text.replace("⠰⠁", "⠰⠜");
            text = text.replace("⠈⠰⠊", "⠰⠊");
            text = text.replace("⠰⠊⠊", "⠰⠔");
            text = text.replace("⠈⠰⠥", "⠰⠥");
            text = text.replace("⠰⠥⠥", "⠰⠳");
            text = text.replace("⠈⠰⠢", "⠰⠢");
            text = text.replace("⠰⠢⠢", "⠰⠑");
            text = text.replace("⠈⠰⠭", "⠰⠭");
            text = text.replace("⠰⠭⠭", "⠰⠕");
            text = text.replace("⠰⠥", "⠰⠪");
            text = text.replace("⠰⠊", "⠰⠌");

            text = text.replace("S", "⠈⠎");
            text = text.replace("⠈⠎⠁", "⠎");
            text = text.replace("⠎⠁", "⠎⠜");
            text = text.replace("⠈⠎⠊", "⠎⠊");
            text = text.replace("⠎⠊⠊", "⠎⠔");
            text = text.replace("⠈⠎⠥", "⠎⠥");
            text = text.replace("⠎⠥⠥", "⠎⠳");
            text = text.replace("⠈⠎⠢", "⠎⠢");
            text = text.replace("⠎⠢⠢", "⠎⠑");
            text = text.replace("⠈⠎⠭", "⠎⠭");
            text = text.replace("⠎⠭⠭", "⠎⠕");
            text = text.replace("⠎⠥", "⠎⠪");
            text = text.replace("⠎⠊", "⠎⠌");

            text = text.replace("h", "⠈⠓");
            text = text.replace("⠈⠓⠁", "⠓");
            text = text.replace("⠓⠁", "⠓⠜");
            text = text.replace("⠈⠓⠊", "⠓⠊");
            text = text.replace("⠓⠊⠊", "⠓⠔");
            text = text.replace("⠈⠓⠥", "⠓⠥");
            text = text.replace("⠓⠥⠥", "⠓⠳");
            text = text.replace("⠈⠓⠢", "⠓⠢");
            text = text.replace("⠓⠢⠢", "⠓⠑");
            text = text.replace("⠈⠓⠭", "⠓⠭");
            text = text.replace("⠓⠭⠭", "⠓⠕");
            text = text.replace("⠓⠥", "⠓⠪");
            text = text.replace("⠓⠊", "⠓⠌");

            text = text.replace("⠈⠉⠈⠓", "⠈⠯");
            text = text.replace("⠈⠯⠁", "⠯");
            text = text.replace("⠯⠁", "⠯⠜");
            text = text.replace("⠈⠯⠊", "⠯⠊");
            text = text.replace("⠯⠊⠊", "⠯⠔");
            text = text.replace("⠈⠯⠥", "⠯⠥");
            text = text.replace("⠯⠥⠥", "⠯⠳");
            text = text.replace("⠈⠯⠢", "⠯⠢");
            text = text.replace("⠯⠢⠢", "⠯⠑");
            text = text.replace("⠈⠯⠭", "⠯⠭");
            text = text.replace("⠯⠭⠭", "⠯⠕");
            text = text.replace("⠯⠥", "⠯⠪");
            text = text.replace("⠯⠊", "⠯⠌");

            text = text.replace("j", "⠈⠚");
            text = text.replace("⠈⠚⠁", "⠚");
            text = text.replace("⠚⠁", "⠚⠜");
            text = text.replace("⠈⠚⠊", "⠚⠊");
            text = text.replace("⠚⠊⠊", "⠚⠔");
            text = text.replace("⠈⠚⠥", "⠚⠥");
            text = text.replace("⠚⠥⠥", "⠚⠳");
            text = text.replace("⠈⠚⠢", "⠚⠢");
            text = text.replace("⠚⠢⠢", "⠚⠑");
            text = text.replace("⠈⠚⠭", "⠚⠭");
            text = text.replace("⠚⠭⠭", "⠚⠕");
            text = text.replace("⠚⠥", "⠚⠪");
            text = text.replace("⠚⠊", "⠚⠌");
            
            if(a==1)
            {
                TamilBrail.TamilBraille.setText(text); 
            }
            else if(a==2)
            {
                TamilBrailTranslateBYEnglish.TamilBraille.setText(text);
            }
             else if(a==3)
            {
                TamilBrailTranslateBYSinhala.TamilBraille.setText(text);
            }
                  
        //***********************************************
    }
}
