/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiOFBCLC;

import ControlersofBCLC.GetingGuisCentral;
import ControlersofBCLC.MovingTitle;
import ControlersofBCLC.NavigationHelpController;
import ControlersofBCLC.Sound;
import ControlersofBCLC.TextToVoice;
import ControlersofBCLC.TextToWavConversion;
import VoieReganition.sphinxtest;
import edu.cmu.sphinx.frontend.util.Microphone;
import edu.cmu.sphinx.recognizer.Recognizer;
import edu.cmu.sphinx.result.Result;
import edu.cmu.sphinx.util.props.ConfigurationManager;
import javax.swing.JOptionPane;

/**
 *
 * @author user pc
 */
public class EnglishDocument1 extends javax.swing.JFrame {

    /**
     * Creates new form SinhalaDocument
     */
    public static String s="";
    public EnglishDocument1()
    {
        initComponents();    
        MovingTitle.movingTitle8(this, "PREPARE ENGLISH DOCUMENT");
        GetingGuisCentral.centreWindow(this);
        gettingdata(s);
        
    }
   public static void gettingdata(String s)
    {
        EnglishDocument.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        EnglishDocument = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        EnglishDocument.setColumns(20);
        EnglishDocument.setFont(new java.awt.Font("Monospaced", 1, 20)); // NOI18N
        EnglishDocument.setRows(5);
        EnglishDocument.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EnglishDocumentKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(EnglishDocument);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Keyboard-Dell-USB-Entry-icon.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/miky.png"))); // NOI18N

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Key Board");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2.setText("Mike");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Amazon-Kindle-icon.png"))); // NOI18N
        jButton3.setText("Listen");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Wait-icon.png"))); // NOI18N
        jButton4.setText("Braille Convert");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/File-Music-icon.png"))); // NOI18N
        jButton5.setText("Save MP3");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/LanguageConverter.png"))); // NOI18N
        jButton6.setText("Language support ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/home-icon.png"))); // NOI18N
        jMenu1.setText("Home");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Arrow-Back-2-icon(formenue).png"))); // NOI18N
        jMenu2.setText("Back    ");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Help-icon.png"))); // NOI18N
        jMenu3.setText(" Help   ");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButton6)
                        .addGap(21, 21, 21)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(8, 8, 8)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jRadioButton2)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton6)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        StartPoint dictionaryService = new StartPoint();
        dictionaryService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String englishDocument = EnglishDocument.getText();
        EnglishBrail.s = englishDocument;
        EnglishDocument.setText("");
        EnglishBrail dictionaryService = new EnglishBrail();
        dictionaryService.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        DocumentLanguage dictionaryService = new DocumentLanguage();
        dictionaryService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void EnglishDocumentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EnglishDocumentKeyReleased
        NavigationHelpController.englishDocumentInterfaceNavigation(evt.getKeyCode(), this);
        Sound.EnglishDocumentPreparingSounds(evt.getKeyCode());

    }//GEN-LAST:event_EnglishDocumentKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        TextToVoice.englishVoice(EnglishDocument.getText());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String englishDocumen = EnglishDocument.getText();
        EnglishBrail.s = englishDocumen;
        String englishDocument = EnglishDocument.getText();
        EnglishLanguageConversion.s = englishDocument;
        EnglishLanguageConversion englishLanguageConversion = new EnglishLanguageConversion();
        englishLanguageConversion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      
        TextToWavConversion.convertEnglishTestToWav(EnglishDocument.getText());
        
        //select path
        /*
         JFileChooser chooser = new JFileChooser();
         chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
         int option = chooser.showSaveDialog(null);
         if (option == JFileChooser.APPROVE_OPTION) {
         // do soemthing
         }*/
//        try {
//
//            PrintWriter writer = new PrintWriter("C:\\Users\\user pc\\Desktop\\the-file-name.wav", "UTF-8");
//            writer.println("The first line");
//            writer.println("The second line");
//            writer.close();
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//        double sampleRate = 44100.0;
//        double frequency = 440;
//        double frequency2 = 90;
//        double amplitude = 1.0;
//        double seconds = 2.0;
//        double twoPiF = 2 * Math.PI * frequency;
//        double piF = Math.PI * frequency2;
//        float[] buffer = new float[(int) (seconds * sampleRate)];
//        for (int sample = 0; sample < buffer.length; sample++) {
//            double time = sample / sampleRate;
//            buffer[sample] = (float) (amplitude * Math.cos((double) piF * time) * Math.sin(twoPiF * time));
//        }
//        final byte[] byteBuffer = new byte[buffer.length * 2];
//        int bufferIndex = 0;
//        for (int i = 0; i < byteBuffer.length; i++) {
//            final int x = (int) (buffer[bufferIndex++] * 32767.0);
//            byteBuffer[i] = (byte) x;
//            i++;
//            byteBuffer[i] = (byte) (x >>> 8);
//        }
//        File out = new File("C:\\Users\\user pc\\Desktop\\the-file-name.wav");
//        boolean bigEndian = false;
//        boolean signed = true;
//        int bits = 16;
//        int channels = 1;
//        AudioFormat format;
//        format = new AudioFormat((float) sampleRate, bits, channels, signed, bigEndian);
//        ByteArrayInputStream bais = new ByteArrayInputStream(byteBuffer);
//        AudioInputStream audioInputStream;
//        audioInputStream = new AudioInputStream(bais, format, buffer.length);
//        try {
//            AudioSystem.write(audioInputStream, AudioFileFormat.Type.WAVE, out);
//            audioInputStream.close();
//        } catch (Exception e) {
//        }
//

    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
       Sound.englishDocumentPrepareHelpSound();
    }//GEN-LAST:event_formWindowOpened

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked

        try 
        {

            ConfigurationManager cm;
            String resultText = null;

            cm = new ConfigurationManager(sphinxtest.class.getResource("helloworld.config.xml"));

            Recognizer recognizer = (Recognizer) cm.lookup("recognizer");
            recognizer.allocate();
            System.out.println("Recognizer on action");

            Microphone microphone = (Microphone) cm.lookup("microphone");
            System.out.println("Microphone on action");
            if (!microphone.startRecording()) {
                EnglishDocument.setText("Cannot start microphone");
                recognizer.deallocate();
                System.exit(1);
            }



            EnglishDocument.setText("Start speaking");
            Result result = recognizer.recognize();
            resultText = result.getBestFinalResultNoFiller();
            if (resultText != null) {
                System.out.println("Starting Word Detection");
                resultText = result.getBestFinalResultNoFiller();
                System.out.println("you said" + resultText + "\n");
                EnglishDocument.setText(resultText + '\n');
                System.out.println("kkk");

            } else {

                EnglishDocument.setText("I can't hear what you said.\n");
                JOptionPane.showMessageDialog(null, "not detected");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jRadioButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnglishDocument1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnglishDocument1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnglishDocument1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnglishDocument1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnglishDocument1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea EnglishDocument;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
