/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiOFBCLC;

import ControlersofBCLC.GetingGuisCentral;
import ControlersofBCLC.GoogleTranslate;
import ControlersofBCLC.MovingTitle;
import ControlersofBCLC.NavigationHelpController;
import ControlersofBCLC.Sound;

/**
 *
 * @author user pc
 */
public class EnglishLanguageConversion extends javax.swing.JFrame {

    /**
     * Creates new form SinhalaBrail
     */
    public static String s = "";
    int count = 0;
    int count1 = 0;

    public EnglishLanguageConversion() {
        initComponents();
        MovingTitle.movingTitle12(this, "ENGLISH lANGUAGE CONVERSION");
        GetingGuisCentral.centreWindow(this);
        gettingdata(s);
    }

    public static void gettingdata(String s) {
        BrailleTextEnglish.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TranslaedEnglishtoSinhala = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        BrailleTextEnglish = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        EnglishToTamilConversion = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/ggg.JPG"))); // NOI18N
        jButton7.setText("Translate Tamil");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        TranslaedEnglishtoSinhala.setColumns(20);
        TranslaedEnglishtoSinhala.setFont(new java.awt.Font("Iskoola Pota", 1, 20)); // NOI18N
        TranslaedEnglishtoSinhala.setRows(5);
        TranslaedEnglishtoSinhala.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TranslaedEnglishtoSinhalaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TranslaedEnglishtoSinhala);

        BrailleTextEnglish.setBackground(new java.awt.Color(255, 255, 204));
        BrailleTextEnglish.setColumns(20);
        BrailleTextEnglish.setFont(new java.awt.Font("Monospaced", 1, 20)); // NOI18N
        BrailleTextEnglish.setRows(5);
        jScrollPane2.setViewportView(BrailleTextEnglish);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Sinhala.jpg"))); // NOI18N
        jButton8.setText("Translate Sinhala");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        EnglishToTamilConversion.setColumns(20);
        EnglishToTamilConversion.setFont(new java.awt.Font("Akshar Unicode", 1, 16)); // NOI18N
        EnglishToTamilConversion.setRows(5);
        jScrollPane3.setViewportView(EnglishToTamilConversion);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/home-icon.png"))); // NOI18N
        jMenu1.setText("Home");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Arrow-Back-2-icon(formenue).png"))); // NOI18N
        jMenu2.setText("Back");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        StartPoint dictionaryService = new StartPoint();
        dictionaryService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        EnglishDocument1.s = BrailleTextEnglish.getText();
        EnglishDocument1 dictionaryService = new EnglishDocument1();
        dictionaryService.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_jMenu2MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
        if (count1 == 0) 
        {
            count1++;
            GoogleTranslate translator = new GoogleTranslate();
            String text = translator.translte(BrailleTextEnglish.getText(), "en", "si");
            TranslaedEnglishtoSinhala.setText(text);
            
        } 
        else 
        {
            SinhalaBrailTBYEnglish.s=TranslaedEnglishtoSinhala.getText();
            count1 = 0;
            SinhalaBrailTBYEnglish sinhalaBrailTBYEnglish = new SinhalaBrailTBYEnglish();
            sinhalaBrailTBYEnglish.setVisible(true);
            this.dispose();

        }





    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        if (count == 0) {
            count++;
            GoogleTranslate translator = new GoogleTranslate();
            String text = translator.translte(BrailleTextEnglish.getText(), "en", "ta");
            EnglishToTamilConversion.setText(text);
            
        } 
        else 
        {
            count = 0;
            TamilBrailTranslateBYEnglish.s=EnglishToTamilConversion.getText();
            TamilBrailTranslateBYEnglish tamilBrailTranslateBYEnglish = new TamilBrailTranslateBYEnglish();
            tamilBrailTranslateBYEnglish.setVisible(true);
            this.dispose();


        }


    }//GEN-LAST:event_jButton7ActionPerformed

    private void TranslaedEnglishtoSinhalaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TranslaedEnglishtoSinhalaKeyReleased
        // TODO add your handling code here:
      ebglishLanguageConversion(evt.getKeyCode(), this);
    }//GEN-LAST:event_TranslaedEnglishtoSinhalaKeyReleased
     public  void ebglishLanguageConversion(int keyCode, EnglishLanguageConversion englishLanguageConversion) {

        if (keyCode == 112 && count1 == 0) {
            count1++;
            GoogleTranslate translator = new GoogleTranslate();
            String text = translator.translte(BrailleTextEnglish.getText(), "en", "si");
             TranslaedEnglishtoSinhala.setText(text);
            //TranslaedEnglishtoSinhala.setText("අම්මා");
        } else if (keyCode == 112 && count1 == 1) {
            SinhalaBrailTBYEnglish.s = TranslaedEnglishtoSinhala.getText();
            count1 = 0;
            SinhalaBrailTBYEnglish sinhalaBrailTBYEnglish = new SinhalaBrailTBYEnglish();
            sinhalaBrailTBYEnglish.setVisible(true);
            englishLanguageConversion.dispose();
        } else if (keyCode == 113 && count == 0) {
            count++;
            GoogleTranslate translator = new GoogleTranslate();
            String text = translator.translte(BrailleTextEnglish.getText(), "en", "ta");
            EnglishToTamilConversion.setText(text);
           // EnglishToTamilConversion.setText("அம்மா");

        } else if (keyCode == 113 && count == 1) {
            count = 0;
            TamilBrailTranslateBYEnglish.s = EnglishToTamilConversion.getText();
            TamilBrailTranslateBYEnglish tamilBrailTranslateBYEnglish = new TamilBrailTranslateBYEnglish();
            tamilBrailTranslateBYEnglish.setVisible(true);
            englishLanguageConversion.dispose();
        } else if (keyCode == 114) {
            EnglishDocument1.s = BrailleTextEnglish.getText();
            EnglishDocument1 dictionaryService = new EnglishDocument1();
            dictionaryService.setVisible(true);
            englishLanguageConversion.dispose();
        } else if (keyCode == 115) {
            Sound.englishLanvageConversionIntroduction();
        }


    }

    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Sound.englishLanvageConversionIntroduction();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnglishLanguageConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnglishLanguageConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnglishLanguageConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnglishLanguageConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnglishLanguageConversion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea BrailleTextEnglish;
    public static javax.swing.JTextArea EnglishToTamilConversion;
    public static javax.swing.JTextArea TranslaedEnglishtoSinhala;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
