/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiOFBCLC;

import ControlersofBCLC.GetingGuisCentral;
import ControlersofBCLC.GoogleTranslate;
import ControlersofBCLC.MovingTitle;
import ControlersofBCLC.Sound;

/**
 *
 * @author user pc
 */
public class SinhalaLanguageConversion extends javax.swing.JFrame {

    /**
     * Creates new form SinhalaBrail
     */
    public static String s = "";
    int count = 0;
    int count1 = 0;
  
    
    public SinhalaLanguageConversion() {
        initComponents();
        MovingTitle.movingTitle10(this, "SINHALA lANGUAGE CONVERSION");
        GetingGuisCentral.centreWindow(this);
        GetSinhalaDocument(s);

    }

    public static void GetSinhalaDocument(String s) {
        SinlalaBrailConvertingtext.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SinhalaToEnglish = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        SinlalaBrailConvertingtext = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        SinhalatoTamil = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/ggg.JPG"))); // NOI18N
        jButton7.setText("Translate Tamil");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        SinhalaToEnglish.setColumns(20);
        SinhalaToEnglish.setFont(new java.awt.Font("Monospaced", 1, 20)); // NOI18N
        SinhalaToEnglish.setRows(5);
        SinhalaToEnglish.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SinhalaToEnglishKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(SinhalaToEnglish);

        SinlalaBrailConvertingtext.setBackground(new java.awt.Color(255, 255, 204));
        SinlalaBrailConvertingtext.setColumns(20);
        SinlalaBrailConvertingtext.setFont(new java.awt.Font("Iskoola Pota", 1, 20)); // NOI18N
        SinlalaBrailConvertingtext.setRows(5);
        jScrollPane2.setViewportView(SinlalaBrailConvertingtext);

        SinhalatoTamil.setColumns(20);
        SinhalatoTamil.setFont(new java.awt.Font("Akshar Unicode", 1, 16)); // NOI18N
        SinhalatoTamil.setRows(5);
        jScrollPane3.setViewportView(SinhalatoTamil);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Letters-icon.png"))); // NOI18N
        jButton8.setText("Translate English");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/home-icon.png"))); // NOI18N
        jMenu1.setText("Home");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Arrow-Back-2-icon(formenue).png"))); // NOI18N
        jMenu2.setText("Back");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addGap(31, 31, 31)
                        .addComponent(jButton7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        StartPoint dictionaryService = new StartPoint();
        dictionaryService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        SinhalaDocument.s = SinlalaBrailConvertingtext.getText();
        SinhalaDocument dictionaryService = new SinhalaDocument();
        dictionaryService.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jMenu2MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (count1 == 0) {
            count1++;
            GoogleTranslate translator = new GoogleTranslate();
            String text = translator.translte(SinlalaBrailConvertingtext.getText(), "si", "en");
            SinhalaToEnglish.setText(text);

        } else {
            EnglishBrailbySinhala.s = SinhalaToEnglish.getText();
            count1 = 0;
            EnglishBrailbySinhala englishBrailbySinhala = new EnglishBrailbySinhala();
            englishBrailbySinhala.setVisible(true);
            this.dispose();

        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (count == 0)
        {
            count++;
            GoogleTranslate translator = new GoogleTranslate();
            String text = translator.translte(SinlalaBrailConvertingtext.getText(), "si", "ta");
            SinhalatoTamil.setText(text);

        }
        else
        {
            count = 0;
            TamilBrailTranslateBYSinhala.s=SinhalatoTamil.getText();
            TamilBrailTranslateBYSinhala tamilBrailTranslateBYSinhala = new TamilBrailTranslateBYSinhala();
            tamilBrailTranslateBYSinhala.setVisible(true);
            this.dispose();
        }
        

    }//GEN-LAST:event_jButton7ActionPerformed

    private void SinhalaToEnglishKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SinhalaToEnglishKeyReleased
        // TODO add your handling code here:
        if ((evt.getKeyCode() == 112) || (evt.getKeyCode() == 113) || (evt.getKeyCode() == 114) || (evt.getKeyCode() == 115) )
        {
            SinhalaLanguageConversion(evt.getKeyCode(), this);
        }
        
    }//GEN-LAST:event_SinhalaToEnglishKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //Sound.sinhalaLanvageConversionIntroduction();
    }//GEN-LAST:event_formWindowOpened
 public  void SinhalaLanguageConversion(int keyCode, SinhalaLanguageConversion sinhalaLanguageConversion)
 {
        if (keyCode == 112 && count1 == 0) 
        {
            count1++;
            GoogleTranslate translator = new GoogleTranslate();
            String text = translator.translte(SinlalaBrailConvertingtext.getText(), "si", "en");
            SinhalaToEnglish.setText(text);
            //SinhalaToEnglish.setText("mother");
        } 
        else if (keyCode == 112 && count1 == 1) 
        {
            EnglishBrailbySinhala.s = SinhalaToEnglish.getText();
            count1 = 0;
            EnglishBrailbySinhala englishBrailbySinhala = new EnglishBrailbySinhala();
            englishBrailbySinhala.setVisible(true);
            this.dispose();
            
        } 
        else if (keyCode == 113 && count == 0) 
        {
            count++;
            GoogleTranslate translator = new GoogleTranslate();
            String text = translator.translte(SinlalaBrailConvertingtext.getText(), "si", "ta");
            SinhalatoTamil.setText(text);
           // SinhalatoTamil.setText("யஅஅயய");

        } 
        else if (keyCode == 113 && count == 1)
        {
            count = 0;
            TamilBrailTranslateBYSinhala.s=SinhalatoTamil.getText();
            TamilBrailTranslateBYSinhala tamilBrailTranslateBYSinhala = new TamilBrailTranslateBYSinhala();
            tamilBrailTranslateBYSinhala.setVisible(true);
            this.dispose();
        } 
        else if (keyCode == 114)
        {

            SinhalaDocument.s = SinlalaBrailConvertingtext.getText();
            SinhalaDocument dictionaryService = new SinhalaDocument();
            dictionaryService.setVisible(true);
            this.dispose();
        } 
        else if (keyCode == 115)
        {
            //play sound clip 2
            
            Sound.sinhalaLanvageConversionIntroduction();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhalaLanguageConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhalaLanguageConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhalaLanguageConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhalaLanguageConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinhalaLanguageConversion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea SinhalaToEnglish;
    public static javax.swing.JTextArea SinhalatoTamil;
    public static javax.swing.JTextArea SinlalaBrailConvertingtext;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
