/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiOFBCLC;

import ControlersofBCLC.GetingGuisCentral;
import ControlersofBCLC.GoogleTranslate;
import ControlersofBCLC.MovingTitle;
import ControlersofBCLC.Sound;


/**
 *
 * @author user pc
 */
public class TamilLanguageConversion extends javax.swing.JFrame {

    /**
     * Creates new form SinhalaBrail
     */
    public static String s = "";
    int count = 0;
    int count1 = 0;
   int count2 = 0;
   int count3 = 0;

    public TamilLanguageConversion() {
        initComponents();
        GetTamilDocument(s);
        MovingTitle.movingTitle11(this, "TAMIL lANGUAGE CONVERSION");
        GetingGuisCentral.centreWindow(this);
    }

    public static void GetTamilDocument(String s) {
        TamilBrailDocument.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TamilToSinhalaConversion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TamilBrailDocument = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        TamilToEnglishConversion = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Sinhala.jpg"))); // NOI18N
        jButton7.setText("Translate Sinhala");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        TamilToSinhalaConversion.setColumns(20);
        TamilToSinhalaConversion.setFont(new java.awt.Font("Iskoola Pota", 1, 20)); // NOI18N
        TamilToSinhalaConversion.setRows(5);
        TamilToSinhalaConversion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TamilToSinhalaConversionKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TamilToSinhalaConversion);

        TamilBrailDocument.setBackground(new java.awt.Color(255, 255, 204));
        TamilBrailDocument.setColumns(20);
        TamilBrailDocument.setFont(new java.awt.Font("Akshar Unicode", 1, 16)); // NOI18N
        TamilBrailDocument.setRows(5);
        jScrollPane2.setViewportView(TamilBrailDocument);

        TamilToEnglishConversion.setColumns(20);
        TamilToEnglishConversion.setFont(new java.awt.Font("Monospaced", 1, 20)); // NOI18N
        TamilToEnglishConversion.setRows(5);
        jScrollPane3.setViewportView(TamilToEnglishConversion);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Letters-icon.png"))); // NOI18N
        jButton8.setText("Translate English");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/home-icon.png"))); // NOI18N
        jMenu1.setText("Home");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Arrow-Back-2-icon(formenue).png"))); // NOI18N
        jMenu2.setText("Back");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addGap(30, 30, 30)
                        .addComponent(jButton8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        StartPoint dictionaryService = new StartPoint();
        dictionaryService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        TamilDocument.s = TamilBrailDocument.getText();
        TamilDocument dictionaryService = new TamilDocument();
        dictionaryService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked
    
    
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (count1 == 0) {
            count1++;
            GoogleTranslate translator = new GoogleTranslate();
            String text = translator.translte(TamilBrailDocument.getText(), "ta", "si");
            TamilToSinhalaConversion.setText(text);

        } else {
            SinhalaBrailTBYTamil.s = TamilToSinhalaConversion.getText();
            count1 = 0;
            SinhalaBrailTBYTamil sinhalaBrailTBYTamil = new SinhalaBrailTBYTamil();
            sinhalaBrailTBYTamil.setVisible(true);
            this.dispose();

        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        if (count == 0) {
            count++;
            GoogleTranslate translator = new GoogleTranslate();
            String text = translator.translte(TamilBrailDocument.getText(), "ta", "en");
            TamilToEnglishConversion.setText(text);
        } else {
            EnglishBrailbyTamil.s = TamilToEnglishConversion.getText();
            count1 = 0;
            EnglishBrailbyTamil englishBrailbyTamil = new EnglishBrailbyTamil();
            englishBrailbyTamil.setVisible(true);
            this.dispose();

        }





    }//GEN-LAST:event_jButton8ActionPerformed

    private void TamilToSinhalaConversionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TamilToSinhalaConversionKeyReleased
        // TODO add your handling code here:
        if ((evt.getKeyCode() == 112) || (evt.getKeyCode() == 113) || (evt.getKeyCode() == 114) || (evt.getKeyCode() == 115) )
        {
            TamilLanguageConversion(evt.getKeyCode(), this);
        }
    }//GEN-LAST:event_TamilToSinhalaConversionKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       // Sound.TamilLanvageConversionIntroduction();
    }//GEN-LAST:event_formWindowOpened

     public  void TamilLanguageConversion(int keyCode, TamilLanguageConversion tamilLanguageConversion) {
        if (keyCode == 112 && count2 == 0) 
        {
            count2++;
            GoogleTranslate translator = new GoogleTranslate();
            String text = translator.translte(TamilBrailDocument.getText(), "ta", "si");
            TamilLanguageConversion.TamilToSinhalaConversion.setText(text);
           // TamilToSinhalaConversion.setText("අම්මා");
        } 
        else if (keyCode == 112 && count2 == 1) 
        {
            SinhalaBrailTBYTamil.s = TamilToSinhalaConversion.getText();
            count2 = 0;
            SinhalaBrailTBYTamil sinhalaBrailTBYTamil = new SinhalaBrailTBYTamil();
            sinhalaBrailTBYTamil.setVisible(true);
            tamilLanguageConversion.dispose();
        } 
        else if (keyCode == 113 && count3 == 0) 
        {
            count3++;
            GoogleTranslate translator = new GoogleTranslate();
            String text = translator.translte(TamilBrailDocument.getText(), "ta", "en");
            TamilToEnglishConversion.setText("father");

        } 
        else if (keyCode == 113 && count3 == 1)
        {
            EnglishBrailbyTamil.s = TamilToEnglishConversion.getText();
            count3 = 0;
            EnglishBrailbyTamil englishBrailbyTamil = new EnglishBrailbyTamil();
            englishBrailbyTamil.setVisible(true);
            tamilLanguageConversion.dispose();
        } 
        else if (keyCode == 114)
        {

           // TamilDocument tamilDocument = new TamilDocument();
            TamilDocument.s = TamilBrailDocument.getText();
            TamilDocument tamilDocument = new TamilDocument();
            tamilDocument.setVisible(true);
            tamilLanguageConversion.dispose();
        } 
        else if (keyCode == 115)
        {
            //play sound clip 2
            Sound.TamilLanvageConversionIntroduction();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TamilLanguageConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TamilLanguageConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TamilLanguageConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TamilLanguageConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TamilLanguageConversion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea TamilBrailDocument;
    public static javax.swing.JTextArea TamilToEnglishConversion;
    public static javax.swing.JTextArea TamilToSinhalaConversion;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
